<a href="https://colab.research.google.com/github/LinaMariaCastro/curso-ia-para-economia/blob/main/clases/3_Analisis_y_visualizacion_datos/4_Preparacion_y_Limpieza_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Inteligencia Artificial con Aplicaciones en Economía I**

- 👩‍🏫 **Profesora:** [Lina María Castro](https://www.linkedin.com/in/lina-maria-castro)  
- 📧 **Email:** [lmcastroco@gmail.com](mailto:lmcastroco@gmail.com)  
- 🎓 **Universidad:** Universidad Externado de Colombia - Facultad de Economía

# 🧹**Preparación y limpieza de datos**

👉 Luego de cargar nuestro dataset, el primer paso es limpiar los datos, para que podamos confiar en ellos. Aunque puede llegar a ser un proceso tedioso, es una parte **crítica** para lograr hacer un correcto y adecuado análisis de los datos.

✅ Resultado: un dataset limpio, coherente y confiable.

**Objetivos de Aprendizaje**

Al finalizar este notebook, serás capaz de:

1. **Identificar y manejar distintos tipos de problemas** en conjuntos de datos  como duplicados, valores faltantes, tipos de datos incorrectos e inconsistencias de formato.
2. **Aplicar técnicas de limpieza para transformar datos crudos** en un formato listo para el análisis, utilizando Pandas.
3. **Comprender las implicaciones económicas y los sesgos** que pueden surgir de una limpieza de datos deficiente o de decisiones de limpieza sesgadas.
4. **Aplicar buenas prácticas** en proyectos de análisis económico y ciencia de datos.

**Introducción**

Imagina que eres un economista del Banco de la República encargado de analizar la inflación en diferentes regiones del país. Recibes un conjunto de datos con precios de productos, pero al revisarlos, notas que algunas entradas tienen precios en diferentes monedas, otras tienen símbolos de moneda ($) que impiden hacer cálculos, y algunas filas están duplicadas o contienen errores evidentes.

Si intentaras calcular la inflación con estos datos sucios, tu resultado sería incorrecto e inútil para la política monetaria. **La limpieza de datos es el proceso de convertir esta "materia prima" defectuosa en un insumo de calidad para que tus modelos económicos y de machine learning sean fiables.** Es similar a la inspección de calidad que se realiza en una fábrica: antes de usar cualquier componente, debes asegurarte de que está en perfectas condiciones.

**Datos crudos Vs Procesados**

![Datos crudos Vs Procesados](https://drive.google.com/uc?id=11i1KhvpeDKMjcxL9rUX7W4pVcjXzz04w)

**Actividad de discusión rápida:** ¿Qué problemas de datos han visto en Excel o en reportes de su carrera?

---

## Importar librerías

In [1]:
import os
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

## Mejorar visualización de los dataframes

In [2]:
# Que muestre todas las columnas
pd.options.display.max_columns = None
# En los dataframes, mostrar los float con dos decimales
pd.options.display.float_format = '{:,.2f}'.format

## Establecer la ruta de los datasets

In [3]:
from google.colab import drive, files
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
path = '/content/drive/MyDrive/Colab Notebooks'

In [7]:
# Para establecer el directorio de los archivos
os.chdir(path)

---

**NOTA:** CONTROL+K+C COMENTA Y DESCOMENTA CTRL+K+U

---

Como ejemplo, vamos a trabajar con un conjunto de datos de la UNCTAD, el cual trae información de los flujos de inversión extranjera directa en el mundo desde 1970 hasta 2021. Este set de datos ha sido modificado con fines educativos.

## Cargar el dataset

In [8]:
df = pd.read_excel('UNCTAD_2021-FDI.xlsx', skiprows=4)

## Exploración inicial del dataset

In [9]:
df

,YEAR,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,DIRECTION,SUBMISSION_DATE,MEASURE,MODE
0,ECONOMY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,0.23,0.45,0.15,0.27,..,..,0.04,-0.24,..,1.20,9,0.18,0.10,..,..,..,..,0.40,..,..,0.00,-0.28,0.36,-0.02,0.02,-0.09,0.69,-1.46,-0.01,6.04,0.17,0.68,50,57.80,186.90,271,238,188.69,46.03,197.51,54.20,57.62,40.86,48.31,42.98,169.15,93.59,51.53,119.44,23.40,12.97,20.60,Inward,"15,072,022.00",US dollars at current prices in milions,Flow
2,Albania,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,20,68,52.97,70.05,90.09,47.54,45.01,41.20,144.27,206.43,133.06,177.10,345.67,264.34,324.42,658.51,974.33,995.93,"1,050.71",876.27,855.44,"1,265.90","1,111.43",945.72,"1,100.67","1,148.89","1,289.69","1,287.97","1,108.16","1,233.92",Inward,"15,072,022.00",US dollars at current prices in milions,Flow
3,Algeria,80.12,0.60,41.49,51,358,119,187,178.45,135.15,25.69,348.67,13.21,-53.57,0.42,0.80,0.40,5.32,3.71,13.02,12.09,40,80,30,0.00,0.00,0.00,270,260,606.60,291.60,280.10,"1,113.11","1,064.96",637.85,884.75,"1,145.62","1,888.46","1,743.63","2,632.05","2,754.12","2,301.23","2,580.63","1,499.45","1,696.87","1,506.73",-584.54,"1,636.30","1,232.34","1,474.59","1,381.81","1,142.64",869.68,Inward,"15,072,022.00",US dollars at current prices in milions,Flow
4,Angola,2.40,1.86,2.16,7.54,6.69,0.05,-1.17,..,1.87,2,37.42,49.05,115.81,104.33,67.14,278,234,119,131,200,-334.50,664.10,288,302,170.10,472,180.63,411.65,1114,"2,471.40",878.60,"2,145.50","1,743.50","3,576.97","2,197.23","-1,303.84",-37.71,-893.34,"1,678.97","2,205.30","-3,227.21","-3,023.77","-1,464.63","-7,120.02","3,657.51","10,028.22",-179.52,"-7,397.30","-6,456.08","-4,098.48","-1,866.47","-4,150.06",Inward,"15,072,022.00",US dollars at current prices in milions,Flow
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
430,Yemen,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,..,..,..,0.20,2.44,0.40,8.20,5.09,4.00,-4.00,-8.56,14.61,28.09,48.90,21.55,23.64,9.25,39.49,229.86,71.88,71.26,57.85,8.52,5.39,11.59,4.43,0.79,5.60,3.61,3.33,..,..,Outward,"22,072,022.00",US dollars at current prices in millions,Flow
431,"Yemen, Democratic",..,..,..,..,..,..,..,..,..,..,..,..,3.51,0.22,0.22,0.47,0.46,..,..,..,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,Outward,"22,072,022.00",US dollars at current prices in millions,Flow
432,"Yugoslavia, Soc. Fed. Rep. of",..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,Outward,"22,072,022.00",US dollars at current prices in millions,Flow
433,Zambia,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,269.56,"1,095.40",-1.40,-701.90,409.47,"-1,706.13",125.09,176.72,-72.05,45.32,696.15,35.43,-453.38,Outward,"22,072,022.00",US dollars at current prices in millions,Flow
434,Zimbabwe,..,..,..,..,..,..,..,..,..,..,..,..,..,6.70,1.90,1.40,0.10,29.80,22.80,0.00,17.30,11.80,4.40,6.70,13,13.40,51,28.20,8.60,9,7.50,4.10,3.20,0.20,0.00,1.10,0.01,3.10,8,..,43.30,42.70,49,27,72,22,28.80,42.23,26.77,30.50,44,55,Outward,"22,072,022.00",US dollars at current prices in millions,Flow

In [10]:
df.shape

(435, 57)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 435 entries, 0 to 434
Data columns (total 57 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YEAR             435 non-null    object
 1   1970             434 non-null    object
 2   1971             434 non-null    object
 3   1972             434 non-null    object
 4   1973             434 non-null    object
 5   1974             434 non-null    object
 6   1975             434 non-null    object
 7   1976             434 non-null    object
 8   1977             434 non-null    object
 9   1978             434 non-null    object
 10  1979             434 non-null    object
 11  1980             434 non-null    object
 12  1981             434 non-null    object
 13  1982             434 non-null    object
 14  1983             434 non-null    object
 15  1984             434 non-null    object
 16  1985             434 non-null    object
 17  1986             434 non-null    object
 18  1987             434 non-null    object
 19  1988             434 non-null    object
 20  1989             434 non-null    object
 21  1990             434 non-null    object
 22  1991             434 non-null    object
 23  1992             434 non-null    object
 24  1993             434 non-null    object
 25  1994             434 non-null    object
 26  1995             434 non-null    object
 27  1996             434 non-null    object
 28  1997             434 non-null    object
 29  1998             434 non-null    object
 30  1999             434 non-null    object
 31  2000             434 non-null    object
 32  2001             434 non-null    object
 33  2002             434 non-null    object
 34  2003             434 non-null    object
 35  2004             434 non-null    object
 36  2005             434 non-null    object
 37  2006             434 non-null    object
 38  2007             434 non-null    object
 39  2008             434 non-null    object
 40  2009             434 non-null    object
 41  2010             434 non-null    object
 42  2011             434 non-null    object
 43  2012             434 non-null    object
 44  2013             434 non-null    object
 45  2014             434 non-null    object
 46  2015             434 non-null    object
 47  2016             434 non-null    object
 48  2017             434 non-null    object
 49  2018             434 non-null    object
 50  2019             434 non-null    object
 51  2020             434 non-null    object
 52  2021             434 non-null    object
 53  DIRECTION        434 non-null    object
 54  SUBMISSION_DATE  434 non-null    float64
 55  MEASURE          434 non-null    object
 56  MODE             434 non-null    object
dtypes: float64(1), object(56)
memory usage: 193.8+ KB

## Eliminar la primera fila

In [12]:
df.drop(index=0, inplace=True)
df.head()

,YEAR,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,DIRECTION,SUBMISSION_DATE,MEASURE,MODE
1,Afghanistan,0.23,0.45,0.15,0.27,..,..,0.04,-0.24,..,1.20,9,0.18,0.10,..,..,..,..,0.40,..,..,0.00,-0.28,0.36,-0.02,0.02,-0.09,0.69,-1.46,-0.01,6.04,0.17,0.68,50,57.80,186.90,271,238,188.69,46.03,197.51,54.20,57.62,40.86,48.31,42.98,169.15,93.59,51.53,119.44,23.40,12.97,20.60,Inward,"15,072,022.00",US dollars at current prices in milions,Flow
2,Albania,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,20,68,52.97,70.05,90.09,47.54,45.01,41.20,144.27,206.43,133.06,177.10,345.67,264.34,324.42,658.51,974.33,995.93,"1,050.71",876.27,855.44,"1,265.90","1,111.43",945.72,"1,100.67","1,148.89","1,289.69","1,287.97","1,108.16","1,233.92",Inward,"15,072,022.00",US dollars at current prices in milions,Flow
3,Algeria,80.12,0.60,41.49,51,358,119,187,178.45,135.15,25.69,348.67,13.21,-53.57,0.42,0.80,0.40,5.32,3.71,13.02,12.09,40,80,30,0.00,0.00,0.00,270,260,606.60,291.60,280.10,"1,113.11","1,064.96",637.85,884.75,"1,145.62","1,888.46","1,743.63","2,632.05","2,754.12","2,301.23","2,580.63","1,499.45","1,696.87","1,506.73",-584.54,"1,636.30","1,232.34","1,474.59","1,381.81","1,142.64",869.68,Inward,"15,072,022.00",US dollars at current prices in milions,Flow
4,Angola,2.40,1.86,2.16,7.54,6.69,0.05,-1.17,..,1.87,2,37.42,49.05,115.81,104.33,67.14,278,234,119,131,200,-334.50,664.10,288,302,170.10,472,180.63,411.65,1114,"2,471.40",878.60,"2,145.50","1,743.50","3,576.97","2,197.23","-1,303.84",-37.71,-893.34,"1,678.97","2,205.30","-3,227.21","-3,023.77","-1,464.63","-7,120.02","3,657.51","10,028.22",-179.52,"-7,397.30","-6,456.08","-4,098.48","-1,866.47","-4,150.06",Inward,"15,072,022.00",US dollars at current prices in milions,Flow
5,Anguilla,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,10.82,6.11,15.42,6.47,11.14,17.58,33.23,21.24,28.06,38.01,39.71,29.62,33.24,29.39,86.73,117.31,142.00,118.88,98.71,43.59,11.40,38.92,43.54,42.15,75.37,82.94,114.84,97.17,209.54,140.22,60.89,80.62,Inward,"15,072,022.00",US dollars at current prices in milions,Flow

## Reiniciar índice para mantener el orden

In [13]:
# Por defecto, esta función toma el índice actual del DataFrame y lo convierte en una columna normal,
# generando un nuevo índice numérico secuencial ($0, 1, 2, ...$).
# Si drop=True: El índice antiguo se elimina por completo. Solo te quedas con el nuevo índice limpio.
#Se usa mucho cuando el índice anterior no tiene información útil (como números desordenados).
df.reset_index(inplace=True, drop=True)
df.head()

,YEAR,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,DIRECTION,SUBMISSION_DATE,MEASURE,MODE
0,Afghanistan,0.23,0.45,0.15,0.27,..,..,0.04,-0.24,..,1.20,9,0.18,0.10,..,..,..,..,0.40,..,..,0.00,-0.28,0.36,-0.02,0.02,-0.09,0.69,-1.46,-0.01,6.04,0.17,0.68,50,57.80,186.90,271,238,188.69,46.03,197.51,54.20,57.62,40.86,48.31,42.98,169.15,93.59,51.53,119.44,23.40,12.97,20.60,Inward,"15,072,022.00",US dollars at current prices in milions,Flow
1,Albania,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,20,68,52.97,70.05,90.09,47.54,45.01,41.20,144.27,206.43,133.06,177.10,345.67,264.34,324.42,658.51,974.33,995.93,"1,050.71",876.27,855.44,"1,265.90","1,111.43",945.72,"1,100.67","1,148.89","1,289.69","1,287.97","1,108.16","1,233.92",Inward,"15,072,022.00",US dollars at current prices in milions,Flow
2,Algeria,80.12,0.60,41.49,51,358,119,187,178.45,135.15,25.69,348.67,13.21,-53.57,0.42,0.80,0.40,5.32,3.71,13.02,12.09,40,80,30,0.00,0.00,0.00,270,260,606.60,291.60,280.10,"1,113.11","1,064.96",637.85,884.75,"1,145.62","1,888.46","1,743.63","2,632.05","2,754.12","2,301.23","2,580.63","1,499.45","1,696.87","1,506.73",-584.54,"1,636.30","1,232.34","1,474.59","1,381.81","1,142.64",869.68,Inward,"15,072,022.00",US dollars at current prices in milions,Flow
3,Angola,2.40,1.86,2.16,7.54,6.69,0.05,-1.17,..,1.87,2,37.42,49.05,115.81,104.33,67.14,278,234,119,131,200,-334.50,664.10,288,302,170.10,472,180.63,411.65,1114,"2,471.40",878.60,"2,145.50","1,743.50","3,576.97","2,197.23","-1,303.84",-37.71,-893.34,"1,678.97","2,205.30","-3,227.21","-3,023.77","-1,464.63","-7,120.02","3,657.51","10,028.22",-179.52,"-7,397.30","-6,456.08","-4,098.48","-1,866.47","-4,150.06",Inward,"15,072,022.00",US dollars at current prices in milions,Flow
4,Anguilla,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,10.82,6.11,15.42,6.47,11.14,17.58,33.23,21.24,28.06,38.01,39.71,29.62,33.24,29.39,86.73,117.31,142.00,118.88,98.71,43.59,11.40,38.92,43.54,42.15,75.37,82.94,114.84,97.17,209.54,140.22,60.89,80.62,Inward,"15,072,022.00",US dollars at current prices in milions,Flow

## Ejercicio: Convertir el valor de la inversión de object a float

In [14]:
df.columns

Index(['YEAR', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021',
       'DIRECTION', 'SUBMISSION_DATE', 'MEASURE', 'MODE'],
      dtype='object')

In [16]:
years = ['1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021']
for year in years:
  df[year] = df[year].astype('float64')

NameError: name 'float64' is not defined

In [17]:
# Filtro para ver el error
df[df['1970']=='..']

,YEAR,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,DIRECTION,SUBMISSION_DATE,MEASURE,MODE
1,Albania,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,20,68,52.97,70.05,90.09,47.54,45.01,41.20,144.27,206.43,133.06,177.10,345.67,264.34,324.42,658.51,974.33,995.93,"1,050.71",876.27,855.44,"1,265.90","1,111.43",945.72,"1,100.67","1,148.89","1,289.69","1,287.97","1,108.16","1,233.92",Inward,"15,072,022.00",US dollars at current prices in milions,Flow
4,Anguilla,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,10.82,6.11,15.42,6.47,11.14,17.58,33.23,21.24,28.06,38.01,39.71,29.62,33.24,29.39,86.73,117.31,142.00,118.88,98.71,43.59,11.40,38.92,43.54,42.15,75.37,82.94,114.84,97.17,209.54,140.22,60.89,80.62,Inward,"15,072,022.00",US dollars at current prices in milions,Flow
5,Antigua and Barbuda,..,..,..,..,..,..,..,2.20,-6.90,8.50,19.60,22.40,23,5,4.40,15.60,22.60,38.60,32.95,43.11,58.75,54.79,19.65,15.24,24.79,31.49,19.35,22.94,22.77,51.79,43.12,98.45,65.87,166.32,80.37,220.96,358.82,338.20,158.78,80.65,96.68,65.16,133.07,94.66,46.26,114.02,97.43,151.27,204.84,127.76,73.53,104.33,Inward,"15,072,022.00",US dollars at current prices in milions,Flow
8,Aruba,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,1.09,12.26,1.30,130.50,184.75,-16.26,-2.57,-58.77,1.12,84.47,195.92,83.58,467.54,-127.93,-266.93,332.12,159.78,-105.65,-207.04,221.35,-469.74,19.55,-10.70,236.87,489.50,-316.42,227.32,208.32,-26.87,27.54,87.86,110.18,-136.12,137.18,134.29,Inward,"15,072,022.00",US dollars at current prices in milions,Flow
13,Bahrain,..,..,..,3.40,0.11,1.32,3.21,0.65,22.97,145.17,-418.04,4.15,28.46,64.10,140.69,101.33,-31.91,-35.90,222.07,180.85,-182.90,619.50,868.62,-275,208.10,430.59,"2,048.20",868.62,-275,453.72,363.56,80.32,217.02,516.70,865.31,"1,048.67","2,914.89",912.23,"2,638.30",257.18,155.85,98.40,"1,545.21","3,728.72","1,518.62",64.89,243.35,"1,426.06","1,654.26","1,501.33","1,021.28","1,765.96",Inward,"15,072,022.00",US dollars at current prices in milions,Flow
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
428,Viet Nam,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,65,85,184,300,700,900,950,1200,1956,1150,1100,1000,480,598,465,380,300,Outward,"25,072,022.00",US dollars at current prices in millions,Flow
430,"Yemen, Democratic",..,..,..,..,..,..,..,..,..,..,..,..,3.51,0.22,0.22,0.47,0.46,..,..,..,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,Outward,"22,072,022.00",US dollars at current prices in millions,Flow
431,"Yugoslavia, Soc. Fed. Rep. of",..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,Outward,"22,072,022.00",US dollars at current prices in millions,Flow
432,Zambia,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,269.56,"1,095.40",-1.40,-701.90,409.47,"-1,706.13",125.09,176.72,-72.05,45.32,696.15,35.43,-453.38,Outward,"22,072,022.00",US dollars at current prices in millions,Flow
433,Zimbabwe,..,..,..,..,..,..,..,..,..,..,..,..,..,6.70,1.90,1.40,0.10,29.80,22.80,0.00,17.30,11.80,4.40,6.70,13,13.40,51,28.20,8.60,9,7.50,4.10,3.20,0.20,0.00,1.10,0.01,3.10,8,..,43.30,42.70,49,27,72,22,28.80,42.23,26.77,30.50,44,55,Outward,"22,072,022.00",US dollars at current prices in millions,Flow

In [19]:
# Reemplazar errores por datos nulos
df.replace('..', np.nan, inplace=True)

In [20]:
# Ya no debe salir el error
df[df['1970']=='..']

Empty DataFrame
Columns: [YEAR, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, DIRECTION, SUBMISSION_DATE, MEASURE, MODE]
Index: []

Vamos a intentarlo nuevamente...

In [21]:
years = ['1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021']
for year in years:
  df[year] = df[year].astype('float64')

ValueError: could not convert string to float: '_'

In [22]:
# Filtro por el error
df[df['1970']=='_']

,YEAR,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,DIRECTION,SUBMISSION_DATE,MEASURE,MODE
7,Armenia,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,2.40,0.80,8,25.32,17.57,51.94,232.38,122.03,104.19,69.87,110.72,122.85,247.14,292.07,466.53,667.67,943.73,760.04,529.32,653.22,496.64,346.09,406.58,184.13,333.73,252.95,266.82,100.95,47.18,378.83,Inward,"15,072,022.00",US dollars at current prices in milions,Flow
11,Azerbaijan,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,NaN,0.01,22,155,591,1051,"1,022.97",510.32,129.93,226.51,"1,392.44",3285,"3,556.10","1,679.92",-583.99,"-4,748.88",14.09,473.31,563,1465,"2,004.60",2632,"4,430.40","4,047.70",4500,2867,1403,"1,503.90",507,"-1,707.70",Inward,"15,072,022.00",US dollars at current prices in milions,Flow
16,Belarus,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,7,17.60,10.50,14.70,104.50,351.60,190.84,444,118.80,95.80,247.10,171.80,163.80,306.60,357.10,"1,807.30","2,187.90","1,876.50","1,393.40","4,002.40","1,429.30","2,229.60","1,827.60","1,667.90","1,237.80","1,278.50",1421,"1,293.10","1,396.80","1,232.94",Inward,"15,072,022.00",US dollars at current prices in milions,Flow
23,Bosnia and Herzegovina,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,NaN,NaN,NaN,NaN,NaN,NaN,66.74,176.78,146.08,118.87,265.17,381.05,511.19,351.19,554.69,"1,819.24","1,001.65",249.95,406.09,496.53,394.87,276.36,550.20,361.14,349.76,491.89,581.38,341.55,395.02,519.07,Inward,"25,072,022.00",US dollars at current prices in milions,Flow
50,Croatia,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,13,118.27,110.33,103.48,485.18,579.58,943.65,"1,425.48",989.65,"1,035.85",984.97,"1,812.65","1,291.41","1,810.33","3,132.77","4,669.38","5,400.06","2,948.11","1,171.94","1,594.17","1,311.97",919.22,"2,899.05",83.64,272.52,539.19,"1,203.43",396.51,136.48,568.85,Inward,"30,072,022.00",US dollars at current prices in milions,Flow
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
410,Timor-Leste,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26,-33,12.67,12.67,12.67,12.67,12.67,NaN,NaN,NaN,693.87,NaN,Outward,"30,072,022.00",US dollars at current prices in millions,Flow
416,Turkmenistan,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Outward,"15,072,022.00",US dollars at current prices in millions,Flow
420,Ukraine,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,NaN,NaN,8,10,-5,42,-4,7,1,23,-5,13,4,275,-133,673,1010,162,736,192,1206,420,111,-95,100,281,-127,842,22,-198,Outward,"15,072,022.00",US dollars at current prices in millions,Flow
425,Uzbekistan,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.95,3.64,3.09,4.32,4.43,4.57,5.82,9.02,1.91,3.09,1.74,2.63,Outward,"22,072,022.00",US dollars at current prices in millions,Flow
429,Yemen,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,NaN,NaN,NaN,0.20,2.44,0.40,8.20,5.09,4.00,-4.00,-8.56,14.61,28.09,48.90,21.55,23.64,9.25,39.49,229.86,71.88,71.26,57.85,8.52,5.39,11.59,4.43,0.79,5.60,3.61,3.33,NaN,NaN,Outward,"22,072,022.00",US dollars at current prices in millions,Flow

In [23]:
# Reemplazar errores por datos nulos
df.replace('_', np.nan, inplace=True)

Vamos a intentar nuevamente...

In [24]:
years = ['1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021']
for year in years:
  df[year] = df[year].astype('float64')

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 434 entries, 0 to 433
Data columns (total 57 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YEAR             434 non-null    object
 1   1970             148 non-null    float64
 2   1971             151 non-null    float64
 3   1972             161 non-null    float64
 4   1973             167 non-null    float64
 5   1974             173 non-null    float64
 6   1975             177 non-null    float64
 7   1976             186 non-null    float64
 8   1977             193 non-null    float64
 9   1978             196 non-null    float64
 10  1979             199 non-null    float64
 11  1980             213 non-null    float64
 12  1981             217 non-null    float64
 13  1982             224 non-null    float64
 14  1983             228 non-null    float64
 15  1984             230 non-null    float64
 16  1985             239 non-null    float64
 17  1986             244 non-null    float64
 18  1987             253 non-null    float64
 19  1988             257 non-null    float64
 20  1989             262 non-null    float64
 21  1990             275 non-null    float64
 22  1991             275 non-null    float64
 23  1992             297 non-null    float64
 24  1993             309 non-null    float64
 25  1994             312 non-null    float64
 26  1995             315 non-null    float64
 27  1996             322 non-null    float64
 28  1997             324 non-null    float64
 29  1998             324 non-null    float64
 30  1999             327 non-null    float64
 31  2000             327 non-null    float64
 32  2001             334 non-null    float64
 33  2002             338 non-null    float64
 34  2003             341 non-null    float64
 35  2004             345 non-null    float64
 36  2005             347 non-null    float64
 37  2006             346 non-null    float64
 38  2007             351 non-null    float64
 39  2008             353 non-null    float64
 40  2009             352 non-null    float64
 41  2010             356 non-null    float64
 42  2011             362 non-null    float64
 43  2012             364 non-null    float64
 44  2013             364 non-null    float64
 45  2014             371 non-null    float64
 46  2015             374 non-null    float64
 47  2016             377 non-null    float64
 48  2017             376 non-null    float64
 49  2018             375 non-null    float64
 50  2019             376 non-null    float64
 51  2020             372 non-null    float64
 52  2021             371 non-null    float64
 53  DIRECTION        434 non-null    object
 54  SUBMISSION_DATE  434 non-null    float64
 55  MEASURE          434 non-null    object
 56  MODE             434 non-null    object
dtypes: float64(53), object(4)
memory usage: 193.4+ KB

Se logró convertir los datos a números! Ya se pueden realizar operaciones con estos.

In [26]:
df['2020'].mean()

np.float64(5021.3543915973605)

In [27]:
df['2020'].describe()

count        372.00
mean       5,021.35
std       28,418.61
min     -191,397.25
25%            6.67
50%          155.06
75%        2,560.59
max      234,919.00
Name: 2020, dtype: float64

In [28]:
df.describe()

,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,SUBMISSION_DATE
count,148.00,151.00,161.00,167.00,173.00,177.00,186.00,193.00,196.00,199.00,213.00,217.00,224.00,228.00,230.00,239.00,244.00,253.00,257.00,262.00,275.00,275.00,297.00,309.00,312.00,315.00,322.00,324.00,324.00,327.00,327.00,334.00,338.00,341.00,345.00,347.00,346.00,351.00,353.00,352.00,356.00,362.00,364.00,364.00,371.00,374.00,377.00,376.00,375.00,376.00,372.00,371.00,434.00
mean,188.26,190.41,191.35,278.12,281.04,308.97,272.67,288.00,373.09,525.02,496.22,559.61,381.03,384.87,467.05,495.23,752.52,"1,103.19","1,349.76","1,649.86","1,628.44","1,291.24","1,249.43","1,509.49","1,751.89","2,253.44","2,464.87","2,975.92","4,271.92","6,691.25","7,903.43","4,489.62","3,275.52","3,273.18","4,822.10","5,260.24","8,274.33","12,060.46","9,472.20","7,206.50","8,233.06","9,438.74","8,050.72","8,633.51","8,011.94","10,889.45","10,088.19","8,934.42","6,671.10","7,326.64","5,021.35","9,242.90","21,383,081.91"
std,690.12,703.74,708.97,"1,065.87","1,026.82","1,209.74","1,050.13","1,043.23","1,452.86","2,331.10","2,099.72","2,233.08","1,376.35","1,258.80","2,089.33","1,913.99","3,167.79","5,019.03","5,405.59","6,619.43","6,046.30","4,276.27","4,336.28","6,225.19","6,303.20","8,104.03","8,786.78","10,163.97","16,361.30","27,280.00","29,990.02","15,658.42","11,108.84","10,709.47","20,200.05","17,250.39","24,326.63","37,504.75","30,559.56","22,220.12","24,433.00","29,822.43","25,375.87","26,069.95","28,737.88","39,774.08","38,761.47","31,369.65","25,012.70","25,736.09","28,418.61","35,875.62","5,246,577.44"
min,-23.00,-111.44,-376.00,-625.91,"-3,732.39",-576.30,-396.60,-451.27,-692.45,"-1,270.52","-3,192.31",-744.13,-391.82,-326.63,-775.45,-448.00,-267.33,"-1,174.90",-595.10,"-1,059.70","-2,519.59",-207.79,"-2,089.40","-1,388.81","-1,519.18","-1,021.95","-1,238.62","-1,565.70","-1,867.07","-1,838.00","-4,550.37","-3,177.89","-6,024.90","-4,959.87","-10,715.97","-35,783.18","-6,505.84","-29,679.43","-16,452.92","-10,084.23","-9,456.02","-3,023.77","-13,397.25","-7,120.02","-151,285.93","-66,821.48","-37,605.82","-27,369.78","-157,406.00","-105,806.79","-191,397.25","-81,055.61","15,072,022.00"
25%,3.06,1.19,1.56,1.35,1.70,3.00,2.05,2.26,1.99,1.15,2.80,1.42,1.02,1.03,1.54,1.06,0.79,1.39,1.90,2.08,1.99,2.71,2.29,2.18,3.00,3.35,4.30,9.87,9.04,9.14,9.77,6.75,8.62,13.80,14.35,20.22,33.69,44.29,49.46,39.04,41.95,41.36,39.94,40.74,28.27,23.78,24.25,17.83,30.49,25.25,6.67,26.28,"15,822,022.00"
50%,18.34,15.93,15.20,13.20,14.30,22.56,11.13,17.10,21.07,17.10,27.70,25.33,17.63,12.31,11.38,14.51,11.10,15.05,20.59,19.44,22.55,25.20,29.20,31.24,42.04,54.09,77.88,96.50,111.31,120.62,125.00,93.47,136.40,180.41,250.00,271.00,394.81,672.84,728.86,428.55,448.15,626.00,603.39,521.25,410.00,342.08,296.70,348.77,340.19,404.50,155.06,263.50,"22,072,022.00"
75%,93.25,97.00,90.43,89.48,106.00,128.00,90.76,97.50,108.61,127.42,129.83,155.10,182.58,159.37,115.58,152.15,166.32,167.30,257.44,422.23,279.94,336.00,303.87,491.00,680.53,714.99,726.48,"1,223.50","1,119.23","1,069.53","1,014.56","1,068.29","1,077.74","1,516.42","1,898.00","2,787.47","5,328.04","6,117.82","4,868.02","3,234.76","3,155.95","4,268.26","3,601.45","3,608.14","3,736.17","3,258.53","2,954.00","3,328.80","3,443.19","3,355.66","2,560.59","3,539.95","25,072,022.00"
max,"7,590.00","7,618.00","7,747.00","11,353.00","9,052.00","14,244.00","11,949.00","11,400.00","16,225.00","26,493.00","19,230.00","25,195.00","13,810.00","11,518.00","25,567.00","20,490.00","36,145.00","59,581.00","58,571.00","69,010.00","50,774.90","32,696.00","42,647.00","77,247.00","73,252.00","92,074.00","84,455.00","103,398.00","174,434.00","283,376.00","314,007.00","159,461.00","134,946.00","129,352.00","294,905.00","182,927.94","237,136.00","393,518.00","308,296.00","287,901.00","277,779.00","396,569.00","318,196.00","303,432.00","333,014.00","467,625.00","459,419.00","327,780.00","203,234.00","232,627.17","234,919.00","403,101.00","30,072,022.00"

## Redondear las cifras de inversión a un decimal

In [29]:
# Redondear el valor de una columna a 1 decimal
df['1970'] = df['1970'].round(1)
df.head()

,YEAR,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,DIRECTION,SUBMISSION_DATE,MEASURE,MODE
0,Afghanistan,0.20,0.45,0.15,0.27,NaN,NaN,0.04,-0.24,NaN,1.20,9.00,0.18,0.10,NaN,NaN,NaN,NaN,0.40,NaN,NaN,0.00,-0.28,0.36,-0.02,0.02,-0.09,0.69,-1.46,-0.01,6.04,0.17,0.68,50.00,57.80,186.90,271.00,238.00,188.69,46.03,197.51,54.20,57.62,40.86,48.31,42.98,169.15,93.59,51.53,119.44,23.40,12.97,20.60,Inward,"15,072,022.00",US dollars at current prices in milions,Flow
1,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.00,68.00,52.97,70.05,90.09,47.54,45.01,41.20,144.27,206.43,133.06,177.10,345.67,264.34,324.42,658.51,974.33,995.93,"1,050.71",876.27,855.44,"1,265.90","1,111.43",945.72,"1,100.67","1,148.89","1,289.69","1,287.97","1,108.16","1,233.92",Inward,"15,072,022.00",US dollars at current prices in milions,Flow
2,Algeria,80.10,0.60,41.49,51.00,358.00,119.00,187.00,178.45,135.15,25.69,348.67,13.21,-53.57,0.42,0.80,0.40,5.32,3.71,13.02,12.09,40.00,80.00,30.00,0.00,0.00,0.00,270.00,260.00,606.60,291.60,280.10,"1,113.11","1,064.96",637.85,884.75,"1,145.62","1,888.46","1,743.63","2,632.05","2,754.12","2,301.23","2,580.63","1,499.45","1,696.87","1,506.73",-584.54,"1,636.30","1,232.34","1,474.59","1,381.81","1,142.64",869.68,Inward,"15,072,022.00",US dollars at current prices in milions,Flow
3,Angola,2.40,1.86,2.16,7.54,6.69,0.05,-1.17,NaN,1.87,2.00,37.42,49.05,115.81,104.33,67.14,278.00,234.00,119.00,131.00,200.00,-334.50,664.10,288.00,302.00,170.10,472.00,180.63,411.65,"1,114.00","2,471.40",878.60,"2,145.50","1,743.50","3,576.97","2,197.23","-1,303.84",-37.71,-893.34,"1,678.97","2,205.30","-3,227.21","-3,023.77","-1,464.63","-7,120.02","3,657.51","10,028.22",-179.52,"-7,397.30","-6,456.08","-4,098.48","-1,866.47","-4,150.06",Inward,"15,072,022.00",US dollars at current prices in milions,Flow
4,Anguilla,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.82,6.11,15.42,6.47,11.14,17.58,33.23,21.24,28.06,38.01,39.71,29.62,33.24,29.39,86.73,117.31,142.00,118.88,98.71,43.59,11.40,38.92,43.54,42.15,75.37,82.94,114.84,97.17,209.54,140.22,60.89,80.62,Inward,"15,072,022.00",US dollars at current prices in milions,Flow

In [30]:
# Redondear el valor de todas las columnas del dataframe a 1 decimal
df = df.round(1)
df.head(3)

,YEAR,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,DIRECTION,SUBMISSION_DATE,MEASURE,MODE
0,Afghanistan,0.20,0.40,0.20,0.30,NaN,NaN,0.00,-0.20,NaN,1.20,9.00,0.20,0.10,NaN,NaN,NaN,NaN,0.40,NaN,NaN,0.00,-0.30,0.40,-0.00,0.00,-0.10,0.70,-1.50,-0.00,6.00,0.20,0.70,50.00,57.80,186.90,271.00,238.00,188.70,46.00,197.50,54.20,57.60,40.90,48.30,43.00,169.10,93.60,51.50,119.40,23.40,13.00,20.60,Inward,"15,072,022.00",US dollars at current prices in milions,Flow
1,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.00,68.00,53.00,70.00,90.10,47.50,45.00,41.20,144.30,206.40,133.10,177.10,345.70,264.30,324.40,658.50,974.30,995.90,"1,050.70",876.30,855.40,"1,265.90","1,111.40",945.70,"1,100.70","1,148.90","1,289.70","1,288.00","1,108.20","1,233.90",Inward,"15,072,022.00",US dollars at current prices in milions,Flow
2,Algeria,80.10,0.60,41.50,51.00,358.00,119.00,187.00,178.40,135.20,25.70,348.70,13.20,-53.60,0.40,0.80,0.40,5.30,3.70,13.00,12.10,40.00,80.00,30.00,0.00,0.00,0.00,270.00,260.00,606.60,291.60,280.10,"1,113.10","1,065.00",637.90,884.70,"1,145.60","1,888.50","1,743.60","2,632.00","2,754.10","2,301.20","2,580.60","1,499.40","1,696.90","1,506.70",-584.50,"1,636.30","1,232.30","1,474.60","1,381.80","1,142.60",869.70,Inward,"15,072,022.00",US dollars at current prices in milions,Flow

## Eliminar columnas innecesarias

### Opción 1

In [31]:
# Vamos a dejar la información solo hasta 2020
df.drop(columns=['2021'], inplace=True)
df.head(3)

,YEAR,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,DIRECTION,SUBMISSION_DATE,MEASURE,MODE
0,Afghanistan,0.20,0.40,0.20,0.30,NaN,NaN,0.00,-0.20,NaN,1.20,9.00,0.20,0.10,NaN,NaN,NaN,NaN,0.40,NaN,NaN,0.00,-0.30,0.40,-0.00,0.00,-0.10,0.70,-1.50,-0.00,6.00,0.20,0.70,50.00,57.80,186.90,271.00,238.00,188.70,46.00,197.50,54.20,57.60,40.90,48.30,43.00,169.10,93.60,51.50,119.40,23.40,13.00,Inward,"15,072,022.00",US dollars at current prices in milions,Flow
1,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.00,68.00,53.00,70.00,90.10,47.50,45.00,41.20,144.30,206.40,133.10,177.10,345.70,264.30,324.40,658.50,974.30,995.90,"1,050.70",876.30,855.40,"1,265.90","1,111.40",945.70,"1,100.70","1,148.90","1,289.70","1,288.00","1,108.20",Inward,"15,072,022.00",US dollars at current prices in milions,Flow
2,Algeria,80.10,0.60,41.50,51.00,358.00,119.00,187.00,178.40,135.20,25.70,348.70,13.20,-53.60,0.40,0.80,0.40,5.30,3.70,13.00,12.10,40.00,80.00,30.00,0.00,0.00,0.00,270.00,260.00,606.60,291.60,280.10,"1,113.10","1,065.00",637.90,884.70,"1,145.60","1,888.50","1,743.60","2,632.00","2,754.10","2,301.20","2,580.60","1,499.40","1,696.90","1,506.70",-584.50,"1,636.30","1,232.30","1,474.60","1,381.80","1,142.60",Inward,"15,072,022.00",US dollars at current prices in milions,Flow

### Opción 2

In [33]:
# Vamos a dejar solo los años de 1980 en adelante
borrar = ['1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979']
df= df.drop(columns=borrar)
df.head(3)

,YEAR,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,DIRECTION,SUBMISSION_DATE,MEASURE,MODE
0,Afghanistan,9.00,0.20,0.10,NaN,NaN,NaN,NaN,0.40,NaN,NaN,0.00,-0.30,0.40,-0.00,0.00,-0.10,0.70,-1.50,-0.00,6.00,0.20,0.70,50.00,57.80,186.90,271.00,238.00,188.70,46.00,197.50,54.20,57.60,40.90,48.30,43.00,169.10,93.60,51.50,119.40,23.40,13.00,Inward,"15,072,022.00",US dollars at current prices in milions,Flow
1,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.00,68.00,53.00,70.00,90.10,47.50,45.00,41.20,144.30,206.40,133.10,177.10,345.70,264.30,324.40,658.50,974.30,995.90,"1,050.70",876.30,855.40,"1,265.90","1,111.40",945.70,"1,100.70","1,148.90","1,289.70","1,288.00","1,108.20",Inward,"15,072,022.00",US dollars at current prices in milions,Flow
2,Algeria,348.70,13.20,-53.60,0.40,0.80,0.40,5.30,3.70,13.00,12.10,40.00,80.00,30.00,0.00,0.00,0.00,270.00,260.00,606.60,291.60,280.10,"1,113.10","1,065.00",637.90,884.70,"1,145.60","1,888.50","1,743.60","2,632.00","2,754.10","2,301.20","2,580.60","1,499.40","1,696.90","1,506.70",-584.50,"1,636.30","1,232.30","1,474.60","1,381.80","1,142.60",Inward,"15,072,022.00",US dollars at current prices in milions,Flow

### Opción 3

In [34]:
# En este caso voy a dejar los datos solo desde el año 2000 en adelante
df = df[['YEAR', '2000', '2001', '2002', '2003', '2004', '2005',
       '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014',
       '2015', '2016', '2017', '2018', '2019', '2020', 'DIRECTION',
       'SUBMISSION_DATE', 'MEASURE', 'MODE']]
df.head(2)

,YEAR,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,DIRECTION,SUBMISSION_DATE,MEASURE,MODE
0,Afghanistan,0.20,0.70,50.00,57.80,186.90,271.00,238.00,188.70,46.00,197.50,54.20,57.60,40.90,48.30,43.00,169.10,93.60,51.50,119.40,23.40,13.00,Inward,"15,072,022.00",US dollars at current prices in milions,Flow
1,Albania,144.30,206.40,133.10,177.10,345.70,264.30,324.40,658.50,974.30,995.90,"1,050.70",876.30,855.40,"1,265.90","1,111.40",945.70,"1,100.70","1,148.90","1,289.70","1,288.00","1,108.20",Inward,"15,072,022.00",US dollars at current prices in milions,Flow

## Cambiar el nombre de una columna

In [35]:
# Vamos a renombrar la columna YEAR
df.rename(columns={'YEAR':"COUNTRY"}, inplace=True)
#df = df.rename(columns={"YEAR": "COUNTRY"})
df.head(2)

,COUNTRY,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,DIRECTION,SUBMISSION_DATE,MEASURE,MODE
0,Afghanistan,0.20,0.70,50.00,57.80,186.90,271.00,238.00,188.70,46.00,197.50,54.20,57.60,40.90,48.30,43.00,169.10,93.60,51.50,119.40,23.40,13.00,Inward,"15,072,022.00",US dollars at current prices in milions,Flow
1,Albania,144.30,206.40,133.10,177.10,345.70,264.30,324.40,658.50,974.30,995.90,"1,050.70",876.30,855.40,"1,265.90","1,111.40",945.70,"1,100.70","1,148.90","1,289.70","1,288.00","1,108.20",Inward,"15,072,022.00",US dollars at current prices in milions,Flow

## Reorganizar columnas

In [36]:
df.columns

Index(['COUNTRY', '2000', '2001', '2002', '2003', '2004', '2005', '2006',
       '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015',
       '2016', '2017', '2018', '2019', '2020', 'DIRECTION', 'SUBMISSION_DATE',
       'MEASURE', 'MODE'],
      dtype='object')

In [37]:
# Colocar el nombre de las columnas en el orden que quiero que queden
df = df[['COUNTRY', 'DIRECTION', 'SUBMISSION_DATE',
       'MEASURE', 'MODE', '2000', '2001', '2002', '2003', '2004', '2005', '2006',
       '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015',
       '2016', '2017', '2018', '2019', '2020']]
df.head(2)

,COUNTRY,DIRECTION,SUBMISSION_DATE,MEASURE,MODE,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Afghanistan,Inward,"15,072,022.00",US dollars at current prices in milions,Flow,0.20,0.70,50.00,57.80,186.90,271.00,238.00,188.70,46.00,197.50,54.20,57.60,40.90,48.30,43.00,169.10,93.60,51.50,119.40,23.40,13.00
1,Albania,Inward,"15,072,022.00",US dollars at current prices in milions,Flow,144.30,206.40,133.10,177.10,345.70,264.30,324.40,658.50,974.30,995.90,"1,050.70",876.30,855.40,"1,265.90","1,111.40",945.70,"1,100.70","1,148.90","1,289.70","1,288.00","1,108.20"

## Procesamiento de Índices

In [38]:
# Volver una columna el índice del df
df = df.set_index('COUNTRY')
df.head()

,DIRECTION,SUBMISSION_DATE,MEASURE,MODE,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
COUNTRY,,,,,,,,,,,,,,,,,,,,,,,,,
Afghanistan,Inward,"15,072,022.00",US dollars at current prices in milions,Flow,0.20,0.70,50.00,57.80,186.90,271.00,238.00,188.70,46.00,197.50,54.20,57.60,40.90,48.30,43.00,169.10,93.60,51.50,119.40,23.40,13.00
Albania,Inward,"15,072,022.00",US dollars at current prices in milions,Flow,144.30,206.40,133.10,177.10,345.70,264.30,324.40,658.50,974.30,995.90,"1,050.70",876.30,855.40,"1,265.90","1,111.40",945.70,"1,100.70","1,148.90","1,289.70","1,288.00","1,108.20"
Algeria,Inward,"15,072,022.00",US dollars at current prices in milions,Flow,280.10,"1,113.10","1,065.00",637.90,884.70,"1,145.60","1,888.50","1,743.60","2,632.00","2,754.10","2,301.20","2,580.60","1,499.40","1,696.90","1,506.70",-584.50,"1,636.30","1,232.30","1,474.60","1,381.80","1,142.60"
Angola,Inward,"15,072,022.00",US dollars at current prices in milions,Flow,878.60,"2,145.50","1,743.50","3,577.00","2,197.20","-1,303.80",-37.70,-893.30,"1,679.00","2,205.30","-3,227.20","-3,023.80","-1,464.60","-7,120.00","3,657.50","10,028.20",-179.50,"-7,397.30","-6,456.10","-4,098.50","-1,866.50"
Anguilla,Inward,"15,072,022.00",US dollars at current prices in milions,Flow,39.70,29.60,33.20,29.40,86.70,117.30,142.00,118.90,98.70,43.60,11.40,38.90,43.50,42.10,75.40,82.90,114.80,97.20,209.50,140.20,60.90

In [39]:
# Convertir en columna el índice del df
df = df.reset_index()
df.head()

,COUNTRY,DIRECTION,SUBMISSION_DATE,MEASURE,MODE,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Afghanistan,Inward,"15,072,022.00",US dollars at current prices in milions,Flow,0.20,0.70,50.00,57.80,186.90,271.00,238.00,188.70,46.00,197.50,54.20,57.60,40.90,48.30,43.00,169.10,93.60,51.50,119.40,23.40,13.00
1,Albania,Inward,"15,072,022.00",US dollars at current prices in milions,Flow,144.30,206.40,133.10,177.10,345.70,264.30,324.40,658.50,974.30,995.90,"1,050.70",876.30,855.40,"1,265.90","1,111.40",945.70,"1,100.70","1,148.90","1,289.70","1,288.00","1,108.20"
2,Algeria,Inward,"15,072,022.00",US dollars at current prices in milions,Flow,280.10,"1,113.10","1,065.00",637.90,884.70,"1,145.60","1,888.50","1,743.60","2,632.00","2,754.10","2,301.20","2,580.60","1,499.40","1,696.90","1,506.70",-584.50,"1,636.30","1,232.30","1,474.60","1,381.80","1,142.60"
3,Angola,Inward,"15,072,022.00",US dollars at current prices in milions,Flow,878.60,"2,145.50","1,743.50","3,577.00","2,197.20","-1,303.80",-37.70,-893.30,"1,679.00","2,205.30","-3,227.20","-3,023.80","-1,464.60","-7,120.00","3,657.50","10,028.20",-179.50,"-7,397.30","-6,456.10","-4,098.50","-1,866.50"
4,Anguilla,Inward,"15,072,022.00",US dollars at current prices in milions,Flow,39.70,29.60,33.20,29.40,86.70,117.30,142.00,118.90,98.70,43.60,11.40,38.90,43.50,42.10,75.40,82.90,114.80,97.20,209.50,140.20,60.90

## Revisar y ajustar las variables categóricas

### Direction

In [40]:
df['DIRECTION'].unique()

array(['Inward', 'Inward  ', 'Outward', '00000Outward'], dtype=object)

In [41]:
df['DIRECTION'].nunique()

4

In [42]:
# Para borrar los espacios en blanco al principio y al final del string
df['DIRECTION']=df['DIRECTION'].str.strip()
df['DIRECTION'].unique()

array(['Inward', 'Outward', '00000Outward'], dtype=object)

In [44]:
# Se quitan los ceros del principio del string
df['DIRECTION'] = df['DIRECTION'].str.lstrip('00000')
df['DIRECTION'].unique()

array(['Inward', 'Outward'], dtype=object)

In [46]:
df['DIRECTION'] = df['DIRECTION'].str.upper()
df['DIRECTION'].unique()

array(['INWARD', 'OUTWARD'], dtype=object)

### Measure

In [47]:
df['MEASURE'].unique()

array(['US dollars at current prices in milions',
       'US dollars at current prices in millions'], dtype=object)

In [48]:
df['MEASURE'] = df['MEASURE'].replace({"US dollars at current prices in milions": "US dollars at current prices in millions"})
df['MEASURE'].unique()

array(['US dollars at current prices in millions'], dtype=object)

In [49]:
df['MEASURE'] = df['MEASURE'].str.upper()
df['MEASURE'].unique()

array(['US DOLLARS AT CURRENT PRICES IN MILLIONS'], dtype=object)

In [50]:
# Dividir en dos partes el string
df['CURRENCY'] = df['MEASURE'].str.split('AT', expand=True)[0]
df['MEASURE_2'] = df['MEASURE'].str.split('AT',expand=True)[1]
df.head(3)

,COUNTRY,DIRECTION,SUBMISSION_DATE,MEASURE,MODE,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,CURRENCY,MEASURE_2
0,Afghanistan,INWARD,"15,072,022.00",US DOLLARS AT CURRENT PRICES IN MILLIONS,Flow,0.20,0.70,50.00,57.80,186.90,271.00,238.00,188.70,46.00,197.50,54.20,57.60,40.90,48.30,43.00,169.10,93.60,51.50,119.40,23.40,13.00,US DOLLARS,CURRENT PRICES IN MILLIONS
1,Albania,INWARD,"15,072,022.00",US DOLLARS AT CURRENT PRICES IN MILLIONS,Flow,144.30,206.40,133.10,177.10,345.70,264.30,324.40,658.50,974.30,995.90,"1,050.70",876.30,855.40,"1,265.90","1,111.40",945.70,"1,100.70","1,148.90","1,289.70","1,288.00","1,108.20",US DOLLARS,CURRENT PRICES IN MILLIONS
2,Algeria,INWARD,"15,072,022.00",US DOLLARS AT CURRENT PRICES IN MILLIONS,Flow,280.10,"1,113.10","1,065.00",637.90,884.70,"1,145.60","1,888.50","1,743.60","2,632.00","2,754.10","2,301.20","2,580.60","1,499.40","1,696.90","1,506.70",-584.50,"1,636.30","1,232.30","1,474.60","1,381.80","1,142.60",US DOLLARS,CURRENT PRICES IN MILLIONS

In [51]:
df['PRICE_TYPE'] = df['MEASURE_2'].str.split('IN',expand=True)[0]
df['UNIT'] = df['MEASURE_2'].str.split('IN',expand=True)[1]
df.head(3)

,COUNTRY,DIRECTION,SUBMISSION_DATE,MEASURE,MODE,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,CURRENCY,MEASURE_2,PRICE_TYPE,UNIT
0,Afghanistan,INWARD,"15,072,022.00",US DOLLARS AT CURRENT PRICES IN MILLIONS,Flow,0.20,0.70,50.00,57.80,186.90,271.00,238.00,188.70,46.00,197.50,54.20,57.60,40.90,48.30,43.00,169.10,93.60,51.50,119.40,23.40,13.00,US DOLLARS,CURRENT PRICES IN MILLIONS,CURRENT PRICES,MILLIONS
1,Albania,INWARD,"15,072,022.00",US DOLLARS AT CURRENT PRICES IN MILLIONS,Flow,144.30,206.40,133.10,177.10,345.70,264.30,324.40,658.50,974.30,995.90,"1,050.70",876.30,855.40,"1,265.90","1,111.40",945.70,"1,100.70","1,148.90","1,289.70","1,288.00","1,108.20",US DOLLARS,CURRENT PRICES IN MILLIONS,CURRENT PRICES,MILLIONS
2,Algeria,INWARD,"15,072,022.00",US DOLLARS AT CURRENT PRICES IN MILLIONS,Flow,280.10,"1,113.10","1,065.00",637.90,884.70,"1,145.60","1,888.50","1,743.60","2,632.00","2,754.10","2,301.20","2,580.60","1,499.40","1,696.90","1,506.70",-584.50,"1,636.30","1,232.30","1,474.60","1,381.80","1,142.60",US DOLLARS,CURRENT PRICES IN MILLIONS,CURRENT PRICES,MILLIONS

In [52]:
df.columns

Index(['COUNTRY', 'DIRECTION', 'SUBMISSION_DATE', 'MEASURE', 'MODE', '2000',
       '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
       '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018',
       '2019', '2020', 'CURRENCY', 'MEASURE_2', 'PRICE_TYPE', 'UNIT'],
      dtype='object')

In [53]:
# Eliminar 'MEASURE' y 'MEASURE_2' y reorganizar columnas
df = df[['COUNTRY', 'MODE', 'DIRECTION', 'CURRENCY', 'UNIT', 'PRICE_TYPE', 'SUBMISSION_DATE', '2000',
       '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
       '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018',
       '2019', '2020']]
df.head(3)

,COUNTRY,MODE,DIRECTION,CURRENCY,UNIT,PRICE_TYPE,SUBMISSION_DATE,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Afghanistan,Flow,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,"15,072,022.00",0.20,0.70,50.00,57.80,186.90,271.00,238.00,188.70,46.00,197.50,54.20,57.60,40.90,48.30,43.00,169.10,93.60,51.50,119.40,23.40,13.00
1,Albania,Flow,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,"15,072,022.00",144.30,206.40,133.10,177.10,345.70,264.30,324.40,658.50,974.30,995.90,"1,050.70",876.30,855.40,"1,265.90","1,111.40",945.70,"1,100.70","1,148.90","1,289.70","1,288.00","1,108.20"
2,Algeria,Flow,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,"15,072,022.00",280.10,"1,113.10","1,065.00",637.90,884.70,"1,145.60","1,888.50","1,743.60","2,632.00","2,754.10","2,301.20","2,580.60","1,499.40","1,696.90","1,506.70",-584.50,"1,636.30","1,232.30","1,474.60","1,381.80","1,142.60"

### Mode

In [54]:
df['MODE'].unique()

array(['Flow', "Flow'''"], dtype=object)

In [55]:
# Se quitan las comillas del final del string
df['MODE'] = df['MODE'].str.rstrip("'''")
df['MODE'].unique()

array(['Flow'], dtype=object)

In [56]:
df['MODE'] = df['MODE'].str.upper()
df['MODE'].unique()

array(['FLOW'], dtype=object)

In [ ]:

df.head()

In [57]:
# Contar el número de caracteres
df["num_caracteres"] = df["MODE"].str.len()
df.head()

,COUNTRY,MODE,DIRECTION,CURRENCY,UNIT,PRICE_TYPE,SUBMISSION_DATE,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,num_caracteres
0,Afghanistan,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,"15,072,022.00",0.20,0.70,50.00,57.80,186.90,271.00,238.00,188.70,46.00,197.50,54.20,57.60,40.90,48.30,43.00,169.10,93.60,51.50,119.40,23.40,13.00,4
1,Albania,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,"15,072,022.00",144.30,206.40,133.10,177.10,345.70,264.30,324.40,658.50,974.30,995.90,"1,050.70",876.30,855.40,"1,265.90","1,111.40",945.70,"1,100.70","1,148.90","1,289.70","1,288.00","1,108.20",4
2,Algeria,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,"15,072,022.00",280.10,"1,113.10","1,065.00",637.90,884.70,"1,145.60","1,888.50","1,743.60","2,632.00","2,754.10","2,301.20","2,580.60","1,499.40","1,696.90","1,506.70",-584.50,"1,636.30","1,232.30","1,474.60","1,381.80","1,142.60",4
3,Angola,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,"15,072,022.00",878.60,"2,145.50","1,743.50","3,577.00","2,197.20","-1,303.80",-37.70,-893.30,"1,679.00","2,205.30","-3,227.20","-3,023.80","-1,464.60","-7,120.00","3,657.50","10,028.20",-179.50,"-7,397.30","-6,456.10","-4,098.50","-1,866.50",4
4,Anguilla,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,"15,072,022.00",39.70,29.60,33.20,29.40,86.70,117.30,142.00,118.90,98.70,43.60,11.40,38.90,43.50,42.10,75.40,82.90,114.80,97.20,209.50,140.20,60.90,4

In [58]:
df["num_caracteres"].unique()

array([4])

In [59]:
df.drop(columns=['num_caracteres'], inplace=True)

In [60]:
df.dtypes

COUNTRY             object
MODE                object
DIRECTION           object
CURRENCY            object
UNIT                object
PRICE_TYPE          object
SUBMISSION_DATE    float64
2000               float64
2001               float64
2002               float64
2003               float64
2004               float64
2005               float64
2006               float64
2007               float64
2008               float64
2009               float64
2010               float64
2011               float64
2012               float64
2013               float64
2014               float64
2015               float64
2016               float64
2017               float64
2018               float64
2019               float64
2020               float64
dtype: object

## Convertir a tipo category

Convertir variables categóricas a tipo category en pandas es una muy buena práctica en ciencia de datos, y tiene varias ventajas importantes:
- Una columna categórica se almacena como códigos numéricos internos en lugar de cadenas de texto repetidas. Esto reduce muchísimo el uso de memoria, sobre todo cuando tienes miles de filas con pocos valores distintos.
- Operaciones como groupby(), value_counts(), merge() son más rápidas en columnas categóricas porque pandas trabaja con los códigos internos (números) en vez de cadenas de texto largas.
- Preparación para Machine Learning: La mayoría de algoritmos no trabajan directamente con strings. Usar category es el primer paso para luego aplicar OneHotEncoding o LabelEncoding fácilmente.
- Permite diferenciar variables que son realmente categóricas de las que son texto libre. Ejemplo: "Bogotá", "Medellín", "Cali" son categorías (ciudades), no simples cadenas de texto. En un directorio de empresas, la columna de razón social no sería categórica porque cada fila tiene un valor diferente.

In [62]:
categorias = ['DIRECTION', 'MODE', 'CURRENCY', 'PRICE_TYPE', 'UNIT']
for categoria in categorias:
  df[categoria]  = df[categoria].astype('category')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 434 entries, 0 to 433
Data columns (total 28 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   COUNTRY          434 non-null    object
 1   MODE             434 non-null    category
 2   DIRECTION        434 non-null    category
 3   CURRENCY         434 non-null    category
 4   UNIT             434 non-null    category
 5   PRICE_TYPE       434 non-null    category
 6   SUBMISSION_DATE  434 non-null    float64
 7   2000             327 non-null    float64
 8   2001             334 non-null    float64
 9   2002             338 non-null    float64
 10  2003             341 non-null    float64
 11  2004             345 non-null    float64
 12  2005             347 non-null    float64
 13  2006             346 non-null    float64
 14  2007             351 non-null    float64
 15  2008             353 non-null    float64
 16  2009             352 non-null    float64
 17  2010             356 non-null    float64
 18  2011             362 non-null    float64
 19  2012             364 non-null    float64
 20  2013             364 non-null    float64
 21  2014             371 non-null    float64
 22  2015             374 non-null    float64
 23  2016             377 non-null    float64
 24  2017             376 non-null    float64
 25  2018             375 non-null    float64
 26  2019             376 non-null    float64
 27  2020             372 non-null    float64
dtypes: category(5), float64(22), object(1)
memory usage: 80.8+ KB

## Revisar y ajustar las variables tipo fecha

Cambiar una columna de string, int o float a datetime tiene las siguientes ventajas:

1. Permite aplicar operaciones de calendario como:
- df["fecha"].dt.year      # año
- df["fecha"].dt.month     # mes
- df["fecha"].dt.day       # día

2. Permite comparaciones y filtros más fáciles. Ejemplo: seleccionar datos de 2023 en adelante.

  df[df["fecha"] >= "2023-01-01"]

  Si fueran strings, hacer este filtro sería muy complicado y propenso a errores.

3. Permite realizar operaciones matemáticas con fechas. Puedes calcular diferencias en días, semanas o meses:

  (df["fecha"].max() - df["fecha"].min()).days

4. Puedes ordenar la serie en orden cronológico.

In [63]:
# Pasar la columna a formato fecha
df['SUBMISSION_DATE'] = pd.to_datetime(df['SUBMISSION_DATE'], format="%d%m%Y")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 434 entries, 0 to 433
Data columns (total 28 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   COUNTRY          434 non-null    object
 1   MODE             434 non-null    category
 2   DIRECTION        434 non-null    category
 3   CURRENCY         434 non-null    category
 4   UNIT             434 non-null    category
 5   PRICE_TYPE       434 non-null    category
 6   SUBMISSION_DATE  434 non-null    datetime64[ns]
 7   2000             327 non-null    float64
 8   2001             334 non-null    float64
 9   2002             338 non-null    float64
 10  2003             341 non-null    float64
 11  2004             345 non-null    float64
 12  2005             347 non-null    float64
 13  2006             346 non-null    float64
 14  2007             351 non-null    float64
 15  2008             353 non-null    float64
 16  2009             352 non-null    float64
 17  2010             356 non-null    float64
 18  2011             362 non-null    float64
 19  2012             364 non-null    float64
 20  2013             364 non-null    float64
 21  2014             371 non-null    float64
 22  2015             374 non-null    float64
 23  2016             377 non-null    float64
 24  2017             376 non-null    float64
 25  2018             375 non-null    float64
 26  2019             376 non-null    float64
 27  2020             372 non-null    float64
dtypes: category(5), datetime64[ns](1), float64(21), object(1)
memory usage: 80.8+ KB

In [64]:
df.head()

,COUNTRY,MODE,DIRECTION,CURRENCY,UNIT,PRICE_TYPE,SUBMISSION_DATE,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Afghanistan,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,0.20,0.70,50.00,57.80,186.90,271.00,238.00,188.70,46.00,197.50,54.20,57.60,40.90,48.30,43.00,169.10,93.60,51.50,119.40,23.40,13.00
1,Albania,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,144.30,206.40,133.10,177.10,345.70,264.30,324.40,658.50,974.30,995.90,"1,050.70",876.30,855.40,"1,265.90","1,111.40",945.70,"1,100.70","1,148.90","1,289.70","1,288.00","1,108.20"
2,Algeria,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,280.10,"1,113.10","1,065.00",637.90,884.70,"1,145.60","1,888.50","1,743.60","2,632.00","2,754.10","2,301.20","2,580.60","1,499.40","1,696.90","1,506.70",-584.50,"1,636.30","1,232.30","1,474.60","1,381.80","1,142.60"
3,Angola,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,878.60,"2,145.50","1,743.50","3,577.00","2,197.20","-1,303.80",-37.70,-893.30,"1,679.00","2,205.30","-3,227.20","-3,023.80","-1,464.60","-7,120.00","3,657.50","10,028.20",-179.50,"-7,397.30","-6,456.10","-4,098.50","-1,866.50"
4,Anguilla,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,39.70,29.60,33.20,29.40,86.70,117.30,142.00,118.90,98.70,43.60,11.40,38.90,43.50,42.10,75.40,82.90,114.80,97.20,209.50,140.20,60.90

In [65]:
# Crear una nueva columna que diga solamente el día de envío de la información
df['DIA'] = df['SUBMISSION_DATE'].dt.day
df.sample(5)

,COUNTRY,MODE,DIRECTION,CURRENCY,UNIT,PRICE_TYPE,SUBMISSION_DATE,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,DIA
324,Kuwait,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-18,-303.20,-242.30,-76.70,"-4,959.90","2,581.30","5,141.80","8,210.50","9,784.20","9,090.60","8,581.80","5,889.80","10,772.90","6,741.30","16,648.00","-10,468.10","5,367.20","4,527.90","9,013.40","3,715.10","-2,696.30","7,988.40",18
264,Comoros,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
388,Seychelles,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-25,7.70,8.50,8.70,8.10,7.60,33.40,8.00,17.80,13.00,5.30,6.20,7.90,15.50,15.80,15.50,10.00,10.30,5.90,5.10,-2.10,10.20,25
261,"China, Macao SAR",FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-26,NaN,10.60,71.10,-4.90,-91.90,60.10,635.90,22.60,-83.50,-10.50,-441.40,120.40,469.20,"1,674.20",681.10,-870.40,"-1,002.30",863.90,140.80,868.80,"1,728.40",26
41,"China, Macao SAR",FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-26,-0.80,160.00,377.70,412.30,484.70,"1,243.30","1,735.70","2,304.50","2,590.90",852.00,"2,831.30",725.60,"3,893.80","4,586.30","3,456.10","1,010.50","1,942.00","1,509.30","2,493.70","6,686.80","-7,104.00",26

In [66]:
df.drop(columns=['DIA'], inplace=True)

In [67]:
# Filtrar los registros que se enviaron después del 22 de julio de 2022
df[df['SUBMISSION_DATE']>"2022-07-22"]

,COUNTRY,MODE,DIRECTION,CURRENCY,UNIT,PRICE_TYPE,SUBMISSION_DATE,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
23,Bosnia and Herzegovina,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-25,146.10,118.90,265.20,381.10,511.20,351.20,554.70,"1,819.20","1,001.60",249.90,406.10,496.50,394.90,276.40,550.20,361.10,349.80,491.90,581.40,341.60,395.00
24,Botswana,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-26,61.20,30.70,403.40,418.00,391.10,278.60,486.40,494.60,520.90,208.70,218.40,293.20,146.50,67.10,515.20,378.60,142.50,260.60,286.00,93.60,31.80
25,Brazil,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-26,"32,779.20","22,457.40","16,590.20","10,143.50","18,145.90","15,066.30","18,822.20","34,584.90","45,058.20","25,948.60","77,686.80","97,421.80","82,059.80","59,089.30","63,845.90","49,961.40","53,700.40","66,584.90","59,802.40","65,386.00","28,318.50"
30,Burundi,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-25,11.70,-0.00,NaN,NaN,0.00,0.60,0.00,0.50,3.80,0.30,0.80,3.40,0.60,7.40,47.10,7.40,0.10,0.30,NaN,1.00,8.50
31,Cabo Verde,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-25,43.40,12.70,38.50,12.40,35.50,53.40,102.90,211.00,309.60,164.80,240.30,266.70,137.70,72.10,183.60,120.40,126.00,111.10,112.30,103.20,73.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
410,Timor-Leste,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.00,-33.00,12.70,12.70,12.70,12.70,12.70,NaN,NaN,NaN,693.90
411,Togo,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-30,0.40,-7.30,2.40,-6.30,-12.60,-14.90,-14.40,-0.70,-15.90,37.40,37.20,"1,059.80",420.30,-20.70,359.00,348.70,257.00,-32.60,70.20,42.80,-112.30
426,Vanuatu,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-25,NaN,NaN,0.70,0.90,1.00,1.00,1.00,1.20,1.20,1.20,1.20,1.00,0.50,0.50,0.50,1.50,0.90,1.10,1.40,0.20,1.80
427,Venezuela (Bolivarian Rep. of),FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-25,521.00,204.00,"1,026.00","1,318.00",619.00,"1,167.00","1,524.00",-495.00,"1,311.00","2,630.00","2,492.00",-370.00,"4,294.00",752.00,"2,373.00",399.00,"1,041.00","2,234.00",661.00,-159.00,358.00
428,Viet Nam,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-25,NaN,NaN,NaN,NaN,NaN,65.00,85.00,184.00,300.00,700.00,900.00,950.00,"1,200.00","1,956.00","1,150.00","1,100.00","1,000.00",480.00,598.00,465.00,380.00

In [68]:
# Para saber el número de días de envío de información que cubre el dataset
(df["SUBMISSION_DATE"].max() - df["SUBMISSION_DATE"].min()).days

15

In [69]:
# Ver el dataset en orden cronológico
df.sort_values(by='SUBMISSION_DATE')

,COUNTRY,MODE,DIRECTION,CURRENCY,UNIT,PRICE_TYPE,SUBMISSION_DATE,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Afghanistan,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,0.20,0.70,50.00,57.80,186.90,271.00,238.00,188.70,46.00,197.50,54.20,57.60,40.90,48.30,43.00,169.10,93.60,51.50,119.40,23.40,13.00
117,Lithuania,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,378.90,445.80,725.00,180.40,844.40,"1,134.60","2,023.40","2,289.40","1,794.00",-448.10,"1,019.50","1,799.00",802.10,573.90,-133.40,"1,055.10",302.60,"1,020.80",976.60,"3,021.60","3,492.30"
118,Lithuania,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,378.90,445.80,725.00,180.40,844.40,"1,134.60","2,023.40","2,289.40","1,794.00",-448.10,"1,019.50","1,799.00",802.10,573.90,-133.40,"1,055.10",302.60,"1,020.80",976.60,"3,021.60","3,492.30"
333,Luxembourg,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,NaN,NaN,"10,217.50",850.70,"6,773.20","8,211.00","10,035.00","71,293.70","11,506.20","8,268.30","23,252.70","10,715.80","-13,397.30","46,620.60","43,420.60","31,919.40","-1,240.80","15,019.00","-25,477.90","-2,575.90","102,624.10"
332,Lithuania,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,3.70,7.10,16.70,38.00,262.90,393.30,308.90,554.20,614.10,554.90,42.20,749.40,540.90,131.90,59.00,377.20,43.20,80.30,704.20,"1,746.50","2,874.30"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379,Saint Kitts and Nevis,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.40,-4.90,-3.00,5.90,28.50,11.70,3.90
378,Saint Helena,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,Ecuador,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-30,-23.40,538.60,783.30,871.50,836.90,493.40,271.40,194.20,"1,057.20",308.60,165.90,646.10,567.40,727.10,776.60,"1,331.30",764.10,629.50,"1,388.70",974.50,"1,104.20"
56,Djibouti,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-30,3.30,3.40,3.40,14.20,38.50,22.20,108.30,195.40,228.90,74.70,36.50,79.00,110.00,286.00,153.00,143.80,160.00,164.90,170.00,175.00,158.20
124,Mali,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-30,82.40,121.70,243.80,132.30,101.00,223.80,83.40,72.80,180.30,748.30,405.90,556.10,397.90,307.90,144.20,275.50,356.50,563.20,467.30,720.60,536.90

## Duplicados

Puede generar un sesgo por sobrevaloración de una observación.

### Detectar duplicados

In [70]:
# Encontrar filas con todos sus valores duplicados (ver sólo el primer valor repetido)
df[df.duplicated()]

,COUNTRY,MODE,DIRECTION,CURRENCY,UNIT,PRICE_TYPE,SUBMISSION_DATE,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
110,Lebanon,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,993.50,"1,453.90","1,336.00","2,860.00","2,483.70","3,321.50","3,131.70","3,376.00","4,002.10","4,378.90","3,708.40","3,137.10","3,111.30","2,661.10","2,862.50","2,159.30","2,568.50","2,522.40","2,658.00","1,361.10","1,306.00"
112,Lesotho,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,32.40,29.70,28.40,43.90,56.70,27.40,24.30,75.60,11.00,91.30,9.50,61.20,56.70,50.40,94.50,206.50,159.20,123.10,128.70,35.70,29.60
114,Liberia,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,20.80,8.30,2.80,372.20,75.40,82.80,107.90,131.60,283.80,217.80,450.00,785.30,984.60,"1,061.30",276.70,627.00,453.20,247.80,129.10,86.70,87.00
116,Libya,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,141.00,-133.00,145.00,143.00,357.00,"1,038.00","2,064.00","3,850.00","3,180.00","3,310.00","1,909.00",NaN,"1,425.00",702.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,Lithuania,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,378.90,445.80,725.00,180.40,844.40,"1,134.60","2,023.40","2,289.40","1,794.00",-448.10,"1,019.50","1,799.00",802.10,573.90,-133.40,"1,055.10",302.60,"1,020.80",976.60,"3,021.60","3,492.30"

In [71]:
# Encontrar filas con todos sus valores duplicados (ver todos los valores repetidos)
df[df.duplicated(keep=False)]

,COUNTRY,MODE,DIRECTION,CURRENCY,UNIT,PRICE_TYPE,SUBMISSION_DATE,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
109,Lebanon,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,993.50,"1,453.90","1,336.00","2,860.00","2,483.70","3,321.50","3,131.70","3,376.00","4,002.10","4,378.90","3,708.40","3,137.10","3,111.30","2,661.10","2,862.50","2,159.30","2,568.50","2,522.40","2,658.00","1,361.10","1,306.00"
110,Lebanon,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,993.50,"1,453.90","1,336.00","2,860.00","2,483.70","3,321.50","3,131.70","3,376.00","4,002.10","4,378.90","3,708.40","3,137.10","3,111.30","2,661.10","2,862.50","2,159.30","2,568.50","2,522.40","2,658.00","1,361.10","1,306.00"
111,Lesotho,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,32.40,29.70,28.40,43.90,56.70,27.40,24.30,75.60,11.00,91.30,9.50,61.20,56.70,50.40,94.50,206.50,159.20,123.10,128.70,35.70,29.60
112,Lesotho,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,32.40,29.70,28.40,43.90,56.70,27.40,24.30,75.60,11.00,91.30,9.50,61.20,56.70,50.40,94.50,206.50,159.20,123.10,128.70,35.70,29.60
113,Liberia,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,20.80,8.30,2.80,372.20,75.40,82.80,107.90,131.60,283.80,217.80,450.00,785.30,984.60,"1,061.30",276.70,627.00,453.20,247.80,129.10,86.70,87.00
114,Liberia,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,20.80,8.30,2.80,372.20,75.40,82.80,107.90,131.60,283.80,217.80,450.00,785.30,984.60,"1,061.30",276.70,627.00,453.20,247.80,129.10,86.70,87.00
115,Libya,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,141.00,-133.00,145.00,143.00,357.00,"1,038.00","2,064.00","3,850.00","3,180.00","3,310.00","1,909.00",NaN,"1,425.00",702.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,Libya,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,141.00,-133.00,145.00,143.00,357.00,"1,038.00","2,064.00","3,850.00","3,180.00","3,310.00","1,909.00",NaN,"1,425.00",702.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,Lithuania,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,378.90,445.80,725.00,180.40,844.40,"1,134.60","2,023.40","2,289.40","1,794.00",-448.10,"1,019.50","1,799.00",802.10,573.90,-133.40,"1,055.10",302.60,"1,020.80",976.60,"3,021.60","3,492.30"
118,Lithuania,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,378.90,445.80,725.00,180.40,844.40,"1,134.60","2,023.40","2,289.40","1,794.00",-448.10,"1,019.50","1,799.00",802.10,573.90,-133.40,"1,055.10",302.60,"1,020.80",976.60,"3,021.60","3,492.30"

In [72]:
# Encontrar duplicados en ciertas columnas, ver todos los valores repetidos
df[df.duplicated(subset='COUNTRY', keep=False)]

,COUNTRY,MODE,DIRECTION,CURRENCY,UNIT,PRICE_TYPE,SUBMISSION_DATE,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Afghanistan,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,0.20,0.70,50.00,57.80,186.90,271.00,238.00,188.70,46.00,197.50,54.20,57.60,40.90,48.30,43.00,169.10,93.60,51.50,119.40,23.40,13.00
1,Albania,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,144.30,206.40,133.10,177.10,345.70,264.30,324.40,658.50,974.30,995.90,"1,050.70",876.30,855.40,"1,265.90","1,111.40",945.70,"1,100.70","1,148.90","1,289.70","1,288.00","1,108.20"
2,Algeria,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,280.10,"1,113.10","1,065.00",637.90,884.70,"1,145.60","1,888.50","1,743.60","2,632.00","2,754.10","2,301.20","2,580.60","1,499.40","1,696.90","1,506.70",-584.50,"1,636.30","1,232.30","1,474.60","1,381.80","1,142.60"
3,Angola,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,878.60,"2,145.50","1,743.50","3,577.00","2,197.20","-1,303.80",-37.70,-893.30,"1,679.00","2,205.30","-3,227.20","-3,023.80","-1,464.60","-7,120.00","3,657.50","10,028.20",-179.50,"-7,397.30","-6,456.10","-4,098.50","-1,866.50"
4,Anguilla,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,39.70,29.60,33.20,29.40,86.70,117.30,142.00,118.90,98.70,43.60,11.40,38.90,43.50,42.10,75.40,82.90,114.80,97.20,209.50,140.20,60.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
429,Yemen,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,-8.60,14.60,28.10,48.90,21.60,23.60,9.20,39.50,229.90,71.90,71.30,57.80,8.50,5.40,11.60,4.40,0.80,5.60,3.60,3.30,NaN
430,"Yemen, Democratic",FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
431,"Yugoslavia, Soc. Fed. Rep. of",FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
432,Zambia,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,269.60,"1,095.40",-1.40,-701.90,409.50,"-1,706.10",125.10,176.70,-72.00,45.30,696.20,35.40
433,Zimbabwe,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,7.50,4.10,3.20,0.20,0.00,1.10,0.00,3.10,8.00,NaN,43.30,42.70,49.00,27.00,72.00,22.00,28.80,42.20,26.80,30.50,44.00

In [73]:
df['COUNTRY'] = df['COUNTRY'].str.strip()

In [74]:
df[df['COUNTRY']=='Lebanon']

,COUNTRY,MODE,DIRECTION,CURRENCY,UNIT,PRICE_TYPE,SUBMISSION_DATE,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
109,Lebanon,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,993.50,"1,453.90","1,336.00","2,860.00","2,483.70","3,321.50","3,131.70","3,376.00","4,002.10","4,378.90","3,708.40","3,137.10","3,111.30","2,661.10","2,862.50","2,159.30","2,568.50","2,522.40","2,658.00","1,361.10","1,306.00"
110,Lebanon,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,993.50,"1,453.90","1,336.00","2,860.00","2,483.70","3,321.50","3,131.70","3,376.00","4,002.10","4,378.90","3,708.40","3,137.10","3,111.30","2,661.10","2,862.50","2,159.30","2,568.50","2,522.40","2,658.00","1,361.10","1,306.00"
328,Lebanon,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-25,137.90,3.90,0.20,611.00,827.10,715.50,874.70,848.10,986.60,"1,125.80",486.80,936.60,"1,030.20","1,975.70","1,240.70",660.20,"1,004.70","1,317.40",631.20,338.00,10.50

In [75]:
# Ver duplicados en varias columnas al tiempo
df[df.duplicated(subset=['COUNTRY', 'MODE', 'DIRECTION'], keep=False)]

,COUNTRY,MODE,DIRECTION,CURRENCY,UNIT,PRICE_TYPE,SUBMISSION_DATE,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
107,Latvia,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-18,328.30,105.20,209.90,279.90,607.20,706.40,"1,663.40","2,324.00","1,264.10",-22.20,419.80,"1,468.00","1,111.40",901.80,896.70,738.90,254.60,710.60,963.70,901.20,"1,013.10"
108,Latvia,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-25,328.30,105.20,209.90,279.90,607.20,706.40,"1,663.40","2,324.00","1,264.10",-22.20,419.80,"1,468.00","1,111.40",901.80,896.70,738.90,254.60,710.60,963.70,901.20,"1,013.10"
109,Lebanon,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,993.50,"1,453.90","1,336.00","2,860.00","2,483.70","3,321.50","3,131.70","3,376.00","4,002.10","4,378.90","3,708.40","3,137.10","3,111.30","2,661.10","2,862.50","2,159.30","2,568.50","2,522.40","2,658.00","1,361.10","1,306.00"
110,Lebanon,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,993.50,"1,453.90","1,336.00","2,860.00","2,483.70","3,321.50","3,131.70","3,376.00","4,002.10","4,378.90","3,708.40","3,137.10","3,111.30","2,661.10","2,862.50","2,159.30","2,568.50","2,522.40","2,658.00","1,361.10","1,306.00"
111,Lesotho,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,32.40,29.70,28.40,43.90,56.70,27.40,24.30,75.60,11.00,91.30,9.50,61.20,56.70,50.40,94.50,206.50,159.20,123.10,128.70,35.70,29.60
112,Lesotho,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,32.40,29.70,28.40,43.90,56.70,27.40,24.30,75.60,11.00,91.30,9.50,61.20,56.70,50.40,94.50,206.50,159.20,123.10,128.70,35.70,29.60
113,Liberia,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,20.80,8.30,2.80,372.20,75.40,82.80,107.90,131.60,283.80,217.80,450.00,785.30,984.60,"1,061.30",276.70,627.00,453.20,247.80,129.10,86.70,87.00
114,Liberia,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,20.80,8.30,2.80,372.20,75.40,82.80,107.90,131.60,283.80,217.80,450.00,785.30,984.60,"1,061.30",276.70,627.00,453.20,247.80,129.10,86.70,87.00
115,Libya,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,141.00,-133.00,145.00,143.00,357.00,"1,038.00","2,064.00","3,850.00","3,180.00","3,310.00","1,909.00",NaN,"1,425.00",702.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,Libya,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,141.00,-133.00,145.00,143.00,357.00,"1,038.00","2,064.00","3,850.00","3,180.00","3,310.00","1,909.00",NaN,"1,425.00",702.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,Lithuania,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,378.90,445.80,725.00,180.40,844.40,"1,134.60","2,023.40","2,289.40","1,794.00",-448.10,"1,019.50","1,799.00",802.10,573.90,-133.40,"1,055.10",302.60,"1,020.80",976.60,"3,021.60","3,492.30"
118,Lithuania,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,378.90,445.80,725.00,180.40,844.40,"1,134.60","2,023.40","2,289.40","1,794.00",-448.10,"1,019.50","1,799.00",802.10,573.90,-133.40,"1,055.10",302.60,"1,020.80",976.60,"3,021.60","3,492.30"

### Ver la cantidad de duplicados que existen

In [76]:
# En general
df.duplicated().sum()

np.int64(5)

In [77]:
# En una columna específica
df['COUNTRY'].duplicated().sum()

np.int64(220)

In [78]:
# En varias columnas
df.duplicated(subset=['COUNTRY','MODE', 'DIRECTION']).sum()

np.int64(6)

### Eliminar duplicados

In [80]:
# Eliminar filas con todos sus valores duplicados, conservando sólo el primer registro
df.drop_duplicates(keep='first', inplace=True)

In [81]:
df.duplicated().sum()

np.int64(0)

In [ ]:
# Eliminar filas con todos sus valores duplicados, conservando sólo el último registro
# df.drop_duplicates(keep='last', inplace=True)

In [ ]:
# Borrar duplicados revisando solo una columna y dejando el último dato que encuentre
# df = df.drop_duplicates(subset="COUNTRY", keep="last")

## Valores faltantes

Implica perdida de información que puede ser muy relevante para el análisis.

### Detectar valores faltantes

In [82]:
len(df)

429

In [83]:
# Ver la cantidad de valores nulos en cada columna
df.isna().sum()

COUNTRY              0
MODE                 0
DIRECTION            0
CURRENCY             0
UNIT                 0
PRICE_TYPE           0
SUBMISSION_DATE      0
2000               107
2001               100
2002                96
2003                93
2004                89
2005                87
2006                88
2007                83
2008                81
2009                82
2010                78
2011                71
2012                70
2013                70
2014                62
2015                59
2016                56
2017                57
2018                58
2019                57
2020                61
dtype: int64

In [84]:
# Para filtrar los nulos de una columna
df[df['2000'].isna()]

,COUNTRY,MODE,DIRECTION,CURRENCY,UNIT,PRICE_TYPE,SUBMISSION_DATE,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
21,Bhutan,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-18,NaN,NaN,2.40,3.40,8.90,6.20,72.20,40.20,4.40,12.80,26.20,33.50,53.80,18.00,23.40,6.50,-33.70,-10.30,6.80,3.50,0.60
47,Cook Islands,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.40,10.50,1.90,11.60,8.00,7.20
51,Curaçao,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.90,54.70,-15.00,150.10,146.40,133.00,172.70,126.90,55.90,158.10
54,Czechoslovakia,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,Ethiopia (...1991),FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
426,Vanuatu,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-25,NaN,NaN,0.70,0.90,1.00,1.00,1.00,1.20,1.20,1.20,1.20,1.00,0.50,0.50,0.50,1.50,0.90,1.10,1.40,0.20,1.80
428,Viet Nam,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-25,NaN,NaN,NaN,NaN,NaN,65.00,85.00,184.00,300.00,700.00,900.00,950.00,"1,200.00","1,956.00","1,150.00","1,100.00","1,000.00",480.00,598.00,465.00,380.00
430,"Yemen, Democratic",FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
431,"Yugoslavia, Soc. Fed. Rep. of",FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
432,Zambia,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,269.60,"1,095.40",-1.40,-701.90,409.50,"-1,706.10",125.10,176.70,-72.00,45.30,696.20,35.40

In [85]:
# Para filtrar los nulos de varias columnas al tiempo
df[df['2000'].isna() & df['2020'].isna()]

,COUNTRY,MODE,DIRECTION,CURRENCY,UNIT,PRICE_TYPE,SUBMISSION_DATE,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
54,Czechoslovakia,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,Ethiopia (...1991),FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,"Germany, Federal Republic of",FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,Micronesia (Federated States of),FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.20,NaN,NaN,NaN,NaN,NaN,NaN
153,"Panama, excluding Canal Zone",FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
216,"Yemen, Democratic",FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
217,"Yugoslavia, Soc. Fed. Rep. of",FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
241,Bhutan,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
247,Brunei Darussalam,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
256,Central African Republic,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-18,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
257,Chad,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
264,Comoros,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
274,Czechoslovakia,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
276,Djibouti,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
279,Ecuador,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
282,Equatorial Guinea,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
283,Eritrea,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
286,Ethiopia,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
287,Ethiopia (...1991),FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
296,"Germany, Federal Republic of",FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
304,Haiti,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
310,Indonesia (...2002),FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
322,"Korea, Dem. People's Rep. of",FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
329,Lesotho,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
337,Maldives,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
340,Marshall Islands,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
344,Micronesia (Federated States of),FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.50,NaN,NaN,NaN,NaN,NaN,NaN
348,Montserrat,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
351,Myanmar,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
353,Nepal,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
365,Palau,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.20,NaN,NaN
367,"Panama, excluding Canal Zone",FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
369,Paraguay,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
377,Rwanda,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.90,NaN,NaN,NaN,NaN,NaN,NaN,3.80,3.50,47.80,15.70,18.00,5.40,NaN
378,Saint Helena,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
389,Sierra Leone,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-25,NaN,NaN,NaN,NaN,NaN,-7.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
395,Somalia,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
397,South Sudan,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
401,Sudan,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
402,Sudan (...2011),FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
403,Suriname,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.10,-0.90,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
406,Syrian Arab Republic,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
408,"Tanzania, United Republic of",FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-30,NaN,0.80,0.20,2.30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
416,Turkmenistan,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
417,Turks and Caicos Islands,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
418,Tuvalu,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
430,"Yemen, Democratic",FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
431,"Yugoslavia, Soc. Fed. Rep. of",FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [86]:
df[df['2000'].isna() | df['2020'].isna()]

,COUNTRY,MODE,DIRECTION,CURRENCY,UNIT,PRICE_TYPE,SUBMISSION_DATE,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
21,Bhutan,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-18,NaN,NaN,2.40,3.40,8.90,6.20,72.20,40.20,4.40,12.80,26.20,33.50,53.80,18.00,23.40,6.50,-33.70,-10.30,6.80,3.50,0.60
47,Cook Islands,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.40,10.50,1.90,11.60,8.00,7.20
51,Curaçao,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.90,54.70,-15.00,150.10,146.40,133.00,172.70,126.90,55.90,158.10
54,Czechoslovakia,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,Ethiopia (...1991),FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
428,Viet Nam,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-25,NaN,NaN,NaN,NaN,NaN,65.00,85.00,184.00,300.00,700.00,900.00,950.00,"1,200.00","1,956.00","1,150.00","1,100.00","1,000.00",480.00,598.00,465.00,380.00
429,Yemen,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,-8.60,14.60,28.10,48.90,21.60,23.60,9.20,39.50,229.90,71.90,71.30,57.80,8.50,5.40,11.60,4.40,0.80,5.60,3.60,3.30,NaN
430,"Yemen, Democratic",FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
431,"Yugoslavia, Soc. Fed. Rep. of",FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
432,Zambia,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,269.60,"1,095.40",-1.40,-701.90,409.50,"-1,706.10",125.10,176.70,-72.00,45.30,696.20,35.40

### Imputar valores faltantes

La elección del método no es trivial y debe basarse en el conocimiento del problema. Imputar con la media podría subestimar la variabilidad de un mercado, mientras que eliminar datos podría generar un sesgo de selección.

### Eliminar filas con valores faltantes

👉 Útil si los faltantes son muy pocos o irrelevantes.

In [87]:
len(df)

429

In [88]:
# Borrar la fila si hay nulos en ciertas columnas
df_2 =df.dropna(subset=['2020'], how='all')
len(df_2)

368

In [89]:
df_2.isna().sum()

COUNTRY             0
MODE                0
DIRECTION           0
CURRENCY            0
UNIT                0
PRICE_TYPE          0
SUBMISSION_DATE     0
2000               59
2001               53
2002               49
2003               44
2004               40
2005               39
2006               39
2007               35
2008               29
2009               30
2010               26
2011               17
2012               15
2013               15
2014                8
2015                3
2016                0
2017                1
2018                3
2019                1
2020                0
dtype: int64

In [90]:
# Borrar la fila si hay nulos en ciertas columnas
# how='any' (Por defecto): Si al menos una de las columnas del subset tiene un valor nulo, la fila se borra.
# how='all': La fila solo se eliminará si todas las columnas especificadas en el subset son nulas al mismo tiempo.
df_3 = df.dropna(subset=['2018', '2019', '2020'], how='all')
len(df_3)

374

In [91]:
df_3.isna().sum()

COUNTRY             0
MODE                0
DIRECTION           0
CURRENCY            0
UNIT                0
PRICE_TYPE          0
SUBMISSION_DATE     0
2000               61
2001               55
2002               51
2003               46
2004               42
2005               41
2006               41
2007               36
2008               31
2009               32
2010               28
2011               19
2012               17
2013               17
2014                9
2015                4
2016                1
2017                2
2018                3
2019                2
2020                6
dtype: int64

In [92]:
df_3

,COUNTRY,MODE,DIRECTION,CURRENCY,UNIT,PRICE_TYPE,SUBMISSION_DATE,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Afghanistan,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,0.20,0.70,50.00,57.80,186.90,271.00,238.00,188.70,46.00,197.50,54.20,57.60,40.90,48.30,43.00,169.10,93.60,51.50,119.40,23.40,13.00
1,Albania,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,144.30,206.40,133.10,177.10,345.70,264.30,324.40,658.50,974.30,995.90,"1,050.70",876.30,855.40,"1,265.90","1,111.40",945.70,"1,100.70","1,148.90","1,289.70","1,288.00","1,108.20"
2,Algeria,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,280.10,"1,113.10","1,065.00",637.90,884.70,"1,145.60","1,888.50","1,743.60","2,632.00","2,754.10","2,301.20","2,580.60","1,499.40","1,696.90","1,506.70",-584.50,"1,636.30","1,232.30","1,474.60","1,381.80","1,142.60"
3,Angola,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,878.60,"2,145.50","1,743.50","3,577.00","2,197.20","-1,303.80",-37.70,-893.30,"1,679.00","2,205.30","-3,227.20","-3,023.80","-1,464.60","-7,120.00","3,657.50","10,028.20",-179.50,"-7,397.30","-6,456.10","-4,098.50","-1,866.50"
4,Anguilla,FLOW,INWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-15,39.70,29.60,33.20,29.40,86.70,117.30,142.00,118.90,98.70,43.60,11.40,38.90,43.50,42.10,75.40,82.90,114.80,97.20,209.50,140.20,60.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427,Venezuela (Bolivarian Rep. of),FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-25,521.00,204.00,"1,026.00","1,318.00",619.00,"1,167.00","1,524.00",-495.00,"1,311.00","2,630.00","2,492.00",-370.00,"4,294.00",752.00,"2,373.00",399.00,"1,041.00","2,234.00",661.00,-159.00,358.00
428,Viet Nam,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-25,NaN,NaN,NaN,NaN,NaN,65.00,85.00,184.00,300.00,700.00,900.00,950.00,"1,200.00","1,956.00","1,150.00","1,100.00","1,000.00",480.00,598.00,465.00,380.00
429,Yemen,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,-8.60,14.60,28.10,48.90,21.60,23.60,9.20,39.50,229.90,71.90,71.30,57.80,8.50,5.40,11.60,4.40,0.80,5.60,3.60,3.30,NaN
432,Zambia,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,269.60,"1,095.40",-1.40,-701.90,409.50,"-1,706.10",125.10,176.70,-72.00,45.30,696.20,35.40
433,Zimbabwe,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,7.50,4.10,3.20,0.20,0.00,1.10,0.00,3.10,8.00,NaN,43.30,42.70,49.00,27.00,72.00,22.00,28.80,42.20,26.80,30.50,44.00

In [93]:
# Borrar todas las filas o registros que tienen datos faltantes en el dataset
df_4 = df.dropna()
len(df_4)

295

In [94]:
df_4.isna().sum()

COUNTRY            0
MODE               0
DIRECTION          0
CURRENCY           0
UNIT               0
PRICE_TYPE         0
SUBMISSION_DATE    0
2000               0
2001               0
2002               0
2003               0
2004               0
2005               0
2006               0
2007               0
2008               0
2009               0
2010               0
2011               0
2012               0
2013               0
2014               0
2015               0
2016               0
2017               0
2018               0
2019               0
2020               0
dtype: int64

#### Reemplazar todos los faltantes por un valor constante

👉 Se usa cuando un valor por defecto tiene sentido (ej. "No aplica", 0 para exportaciones).

In [95]:
# Llenar los valores nulos con cero
df['2000'] = df['2000'].fillna(0)
df.tail()

,COUNTRY,MODE,DIRECTION,CURRENCY,UNIT,PRICE_TYPE,SUBMISSION_DATE,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
429,Yemen,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,-8.60,14.60,28.10,48.90,21.60,23.60,9.20,39.50,229.90,71.90,71.30,57.80,8.50,5.40,11.60,4.40,0.80,5.60,3.60,3.30,NaN
430,"Yemen, Democratic",FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
431,"Yugoslavia, Soc. Fed. Rep. of",FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
432,Zambia,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,269.60,"1,095.40",-1.40,-701.90,409.50,"-1,706.10",125.10,176.70,-72.00,45.30,696.20,35.40
433,Zimbabwe,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,7.50,4.10,3.20,0.20,0.00,1.10,0.00,3.10,8.00,NaN,43.30,42.70,49.00,27.00,72.00,22.00,28.80,42.20,26.80,30.50,44.00

In [96]:
# Llenar los valores nulos con un string
df['2001'] = df['2001'].fillna('No aplica')
df.tail()

,COUNTRY,MODE,DIRECTION,CURRENCY,UNIT,PRICE_TYPE,SUBMISSION_DATE,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
429,Yemen,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,-8.60,14.60,28.10,48.90,21.60,23.60,9.20,39.50,229.90,71.90,71.30,57.80,8.50,5.40,11.60,4.40,0.80,5.60,3.60,3.30,NaN
430,"Yemen, Democratic",FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,0.00,No aplica,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
431,"Yugoslavia, Soc. Fed. Rep. of",FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,0.00,No aplica,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
432,Zambia,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,0.00,No aplica,NaN,NaN,NaN,NaN,NaN,NaN,NaN,269.60,"1,095.40",-1.40,-701.90,409.50,"-1,706.10",125.10,176.70,-72.00,45.30,696.20,35.40
433,Zimbabwe,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,7.50,4.10,3.20,0.20,0.00,1.10,0.00,3.10,8.00,NaN,43.30,42.70,49.00,27.00,72.00,22.00,28.80,42.20,26.80,30.50,44.00

#### Imputación con estadísticas de la columna

👉 Muy usado en economía. Por ejemplo, la media/mediana para ingresos.

In [97]:
# Llenar los valores nulos con la media de la columna
df['2002'] =df['2002'].fillna(df['2002'].mean())
df.tail()

,COUNTRY,MODE,DIRECTION,CURRENCY,UNIT,PRICE_TYPE,SUBMISSION_DATE,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
429,Yemen,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,-8.60,14.60,28.10,48.90,21.60,23.60,9.20,39.50,229.90,71.90,71.30,57.80,8.50,5.40,11.60,4.40,0.80,5.60,3.60,3.30,NaN
430,"Yemen, Democratic",FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,0.00,No aplica,"3,317.98",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
431,"Yugoslavia, Soc. Fed. Rep. of",FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,0.00,No aplica,"3,317.98",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
432,Zambia,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,0.00,No aplica,"3,317.98",NaN,NaN,NaN,NaN,NaN,NaN,269.60,"1,095.40",-1.40,-701.90,409.50,"-1,706.10",125.10,176.70,-72.00,45.30,696.20,35.40
433,Zimbabwe,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,7.50,4.10,3.20,0.20,0.00,1.10,0.00,3.10,8.00,NaN,43.30,42.70,49.00,27.00,72.00,22.00,28.80,42.20,26.80,30.50,44.00

#### Imputación con valores vecinos

👉 Muy útil en series de tiempo (ejemplo: inflación mensual, PIB trimestral).

##### Forward fill (ffill): usa el último valor válido anterior

In [98]:
df['2003'].fillna(method="ffill", inplace=True)
df.tail()

,COUNTRY,MODE,DIRECTION,CURRENCY,UNIT,PRICE_TYPE,SUBMISSION_DATE,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
429,Yemen,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,-8.60,14.60,28.10,48.90,21.60,23.60,9.20,39.50,229.90,71.90,71.30,57.80,8.50,5.40,11.60,4.40,0.80,5.60,3.60,3.30,NaN
430,"Yemen, Democratic",FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,0.00,No aplica,"3,317.98",48.90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
431,"Yugoslavia, Soc. Fed. Rep. of",FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,0.00,No aplica,"3,317.98",48.90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
432,Zambia,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,0.00,No aplica,"3,317.98",48.90,NaN,NaN,NaN,NaN,NaN,269.60,"1,095.40",-1.40,-701.90,409.50,"-1,706.10",125.10,176.70,-72.00,45.30,696.20,35.40
433,Zimbabwe,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,7.50,4.10,3.20,0.20,0.00,1.10,0.00,3.10,8.00,NaN,43.30,42.70,49.00,27.00,72.00,22.00,28.80,42.20,26.80,30.50,44.00

##### Backward fill (bfill): usa el siguiente valor válido

In [99]:
df["2004"].fillna(method="bfill", inplace=True)
df.tail()

,COUNTRY,MODE,DIRECTION,CURRENCY,UNIT,PRICE_TYPE,SUBMISSION_DATE,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
429,Yemen,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,-8.60,14.60,28.10,48.90,21.60,23.60,9.20,39.50,229.90,71.90,71.30,57.80,8.50,5.40,11.60,4.40,0.80,5.60,3.60,3.30,NaN
430,"Yemen, Democratic",FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,0.00,No aplica,"3,317.98",48.90,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
431,"Yugoslavia, Soc. Fed. Rep. of",FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,0.00,No aplica,"3,317.98",48.90,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
432,Zambia,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,0.00,No aplica,"3,317.98",48.90,0.00,NaN,NaN,NaN,NaN,269.60,"1,095.40",-1.40,-701.90,409.50,"-1,706.10",125.10,176.70,-72.00,45.30,696.20,35.40
433,Zimbabwe,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,7.50,4.10,3.20,0.20,0.00,1.10,0.00,3.10,8.00,NaN,43.30,42.70,49.00,27.00,72.00,22.00,28.80,42.20,26.80,30.50,44.00

#### Interpolación

Calcula valores intermedios automáticamente

👉 Útil en datos económicos continuos, como tasas de crecimiento. Útil en series de tiempo.

In [100]:
df['2005'].interpolate(method='linear', inplace=True)
df.tail()

,COUNTRY,MODE,DIRECTION,CURRENCY,UNIT,PRICE_TYPE,SUBMISSION_DATE,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
429,Yemen,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,-8.60,14.60,28.10,48.90,21.60,23.60,9.20,39.50,229.90,71.90,71.30,57.80,8.50,5.40,11.60,4.40,0.80,5.60,3.60,3.30,NaN
430,"Yemen, Democratic",FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,0.00,No aplica,"3,317.98",48.90,0.00,17.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
431,"Yugoslavia, Soc. Fed. Rep. of",FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,0.00,No aplica,"3,317.98",48.90,0.00,12.35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
432,Zambia,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,0.00,No aplica,"3,317.98",48.90,0.00,6.73,NaN,NaN,NaN,269.60,"1,095.40",-1.40,-701.90,409.50,"-1,706.10",125.10,176.70,-72.00,45.30,696.20,35.40
433,Zimbabwe,FLOW,OUTWARD,US DOLLARS,MILLIONS,CURRENT PRICES,2022-07-22,7.50,4.10,3.20,0.20,0.00,1.10,0.00,3.10,8.00,NaN,43.30,42.70,49.00,27.00,72.00,22.00,28.80,42.20,26.80,30.50,44.00