<a href="https://colab.research.google.com/github/LinaMariaCastro/curso-ia-para-economia/blob/main/clases/3_Analisis_y_visualizacion_datos/5_Manipulacion_y_Transformacion_de_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install wbdata

Requirement already satisfied: wbdata in /usr/local/lib/python3.13/dist-packages (1.1.0)
Requirement already satisfied: appdirs<2,>=1.4 in /usr/local/lib/python3.13/dist-packages (from wbdata) (1.4.4)
Requirement already satisfied: backoff<3,>=2.2.1 in /usr/local/lib/python3.13/dist-packages (from wbdata) (2.2.1)
Requirement already satisfied: cachetools<6,>=5.3.2 in /usr/local/lib/python3.13/dist-packages (from wbdata) (5.5.2)
Requirement already satisfied: dateparser<2,>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from wbdata) (1.4.3)
Requirement already satisfied: decorator<6,>=5.1.1 in /usr/local/lib/python3.13/dist-packages (from wbdata) (5.3.1)
Requirement already satisfied: requests<3,>=2.0 in /usr/local/lib/python3.13/dist-packages (from wbdata) (2.32.4)
Requirement already satisfied: shelved-cache<0.4,>=0.3.1 in /usr/local/lib/python3.13/dist-packages (from wbdata) (0.3.1)
Requirement already satisfied: tabulate<1,>=0.8.5 in /usr/local/lib/python3.13/dist-packages (from wbdata) (0.9.0)
Requirement already satisfied: python-dateutil>=2.7.0 in /usr/local/lib/python3.13/dist-packages (from dateparser<2,>=1.2.0->wbdata) (2.9.0.post0)
Requirement already satisfied: pytz>=2024.2 in /usr/local/lib/python3.13/dist-packages (from dateparser<2,>=1.2.0->wbdata) (2025.2)
Requirement already satisfied: regex>=2024.9.11 in /usr/local/lib/python3.13/dist-packages (from dateparser<2,>=1.2.0->wbdata) (2025.11.3)
Requirement already satisfied: tzlocal>=0.2 in /usr/local/lib/python3.13/dist-packages (from dateparser<2,>=1.2.0->wbdata) (5.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.0->wbdata) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.0->wbdata) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.0->wbdata) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.0->wbdata) (2026.7.22)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7.0->dateparser<2,>=1.2.0->wbdata) (1.17.0)

# **Inteligencia Artificial con Aplicaciones en Economía I**

- 👩‍🏫 **Profesora:** [Lina María Castro](https://www.linkedin.com/in/lina-maria-castro)  
- 📧 **Email:** [lmcastroco@gmail.com](mailto:lmcastroco@gmail.com)  
- 🎓 **Universidad:** Universidad Externado de Colombia - Facultad de Economía

# 🪄**Manipulación y transformación de datos**

👉 Ahora que los datos están limpios, toca organizarlos para analizarlos.

✅ Resultado: un dataset estructurado para responder preguntas económicas.

**Objetivos de Aprendizaje:**

Al finalizar este notebook, serás capaz de:

1. **Organizar y filtrar datos** para aislar la información más relevante para una pregunta de investigación económica.

2. **Agregar y resumir datos** para calcular estadísticas descriptivas a nivel de grupo (e.g., por región, por nivel de ingreso).

3. **Remodelar y transformar tablas de datos** para pasar de formatos anchos a largos y viceversa, una habilidad crucial para preparar datos para modelos econométricos y visualizaciones.

**Introducción**

Imagina que eres un economista recién contratado en el Banco Mundial. Tu primer encargo es analizar la relación entre el Gasto Público en Educación (% del PIB) y el Crecimiento del PIB per cápita para diferentes regiones del mundo durante la última década.

Recibes un enorme archivo csv con miles de filas y columnas, mezclando países, años e indicadores de todo tipo. No puedes simplemente introducir eso en un modelo. Primero, necesitas esculpir y analizar tus datos. Necesitas:

- Ordenar los países para ver los que más y menos invierten.

- Filtrar para quedarte solo con los años y los indicadores relevantes.

- Agrupar por región para calcular el gasto promedio y ver si África Subsahariana invierte, en promedio, más o menos que América Latina.

- Pivotar la tabla para que cada fila sea un país y cada columna un año, permitiéndote ver la evolución de un vistazo.

Estas no son solo "funciones de pandas"; son las herramientas diarias de un economista.

## Importar librerías

In [2]:
import os
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

## Mejorar visualización de los dataframes

In [3]:
# Que muestre todas las columnas
pd.options.display.max_columns = None
# En los dataframes, mostrar los float con dos decimales
pd.options.display.float_format = '{:,.2f}'.format

## Cargar el dataset

Como ejemplo, usaremos un **dataset real del Banco Mundial** que contiene indicadores de desarrollo. Esto nos permitirá realizar un análisis que un economista haría en su día a día.

Utilizaremos la API del Banco Mundial para obtener los datos.

In [4]:
import wbdata

In [5]:
# Listar bases de datos disponibles en el Banco Mundial
# Nos interesa World Development Indicators
wbdata.get_sources()

  id  name
----  --------------------------------------------------------------------
   1  Doing Business
   2  World Development Indicators
   3  Worldwide Governance Indicators
   5  Subnational Malnutrition Database
   6  International Debt Statistics
  11  Africa Development Indicators
  12  Education Statistics
  13  Enterprise Surveys
  14  Gender Statistics
  15  Global Economic Monitor
  16  Health Nutrition and Population Statistics
  18  IDA Results Measurement System
  19  Millennium Development Goals
  20  Quarterly Public Sector Debt
  22  Quarterly External Debt Statistics SDDS
  23  Quarterly External Debt Statistics GDDS
  25  Jobs
  27  Global Economic Prospects
  28  Global Findex database
  29  The Atlas of Social Protection: Indicators of Resilience and Equity
  30  Exporter Dynamics Database – Indicators at Country-Year Level
  31  Country Policy and Institutional Assessment
  32  Global Financial Development
  33  G20 Financial Inclusion Indicators
  34  Global Partnership for Education
  35  Sustainable Energy for All
  37  LAC Equity Lab
  38  Subnational Poverty
  39  Health Nutrition and Population Statistics by Wealth Quintile
  40  Population estimates and projections
  41  Country Partnership Strategy for India (FY2013 - 17)
  43  Adjusted Net Savings
  45  Indonesia Database for Policy and Economic Research
  46  Sustainable Development Goals
  50  Subnational Population
  54  Joint External Debt Hub
  57  WDI Database Archives
  58  Universal Health Coverage
  59  Wealth Accounts
  60  Economic Fitness
  61  PPPs Regulatory Quality
  62  International Comparison Program (ICP) 2011
  63  Human Capital Index
  64  Worldwide Bureaucracy Indicators
  65  Health Equity and Financial Protection Indicators
  66  Logistics Performance Index
  67  PEFA 2011
  68  PEFA 2016
  69  Global Financial Inclusion and Consumer Protection Survey
  70  Economic Fitness 2
  71  International Comparison Program (ICP) 2005
  73  Global Financial Inclusion and Consumer Protection Survey (Internal)
  75  Environment, Social and Governance (ESG) Data
  76  Remittance Prices Worldwide (Sending Countries)
  77  Remittance Prices Worldwide (Receiving Countries)
  78  ICP 2017
  79  PEFA_GRPFM
  80  Gender Disaggregated Labor Database (GDLD)
  81  International Debt Statistics: DSSI
  82  Global Public Procurement
  83  Statistical Performance Indicators (SPI)
  84  Education Policy
  85  PEFA_2021_SNG
  86  Global Jobs Indicators Database (JOIN)
  87  Country Climate and Development Report (CCDR)
  88  Food Prices for Nutrition
  89  Identification for Development (ID4D) Data
  90  ICP 2021
  91  PEFA_CRPFM
  92  Disability Data Hub (DDH)
  93  FPN Datahub Archive

In [6]:
# Listar indicadores disponibles en World Development Indicators
wbdata.get_indicators(source=2)

id                          name
--------------------------  ---------------------------------------------------------------------------------------------------------------------------------------------
AG.CON.FERT.PT.ZS           Fertilizer consumption (% of fertilizer production)
AG.CON.FERT.ZS              Fertilizer consumption (kilograms per hectare of arable land)
AG.LND.AGRI.K2              Agricultural land (sq. km)
AG.LND.AGRI.ZS              Agricultural land (% of land area)
AG.LND.ARBL.HA              Arable land (hectares)
AG.LND.ARBL.HA.PC           Arable land (hectares per person)
AG.LND.ARBL.ZS              Arable land (% of land area)
AG.LND.CREL.HA              Land under cereal production (hectares)
AG.LND.CROP.ZS              Permanent cropland (% of land area)
AG.LND.EL5M.RU.K2           Rural land area where elevation is below 5 meters (sq. km)
AG.LND.EL5M.RU.ZS           Rural land area where elevation is below 5 meters (% of total land area)
AG.LND.EL5M.UR.K2           Urban land area where elevation is below 5 meters (sq. km)
AG.LND.EL5M.UR.ZS           Urban land area where elevation is below 5 meters (% of total land area)
AG.LND.EL5M.ZS              Land area where elevation is below 5 meters (% of total land area)
AG.LND.FRST.K2              Forest area (sq. km)
AG.LND.FRST.ZS              Forest area (% of land area)
AG.LND.IRIG.AG.ZS           Agricultural irrigated land (% of total agricultural land)
AG.LND.PRCP.MM              Average precipitation in depth (mm per year)
AG.LND.TOTL.K2              Land area (sq. km)
AG.LND.TOTL.RU.K2           Rural land area (sq. km)
AG.LND.TOTL.UR.K2           Urban land area (sq. km)
AG.PRD.CREL.MT              Cereal production (metric tons)
AG.PRD.CROP.XD              Crop production index (2014-2016 = 100)
AG.PRD.FOOD.XD              Food production index (2014-2016 = 100)
AG.PRD.LVSK.XD              Livestock production index (2014-2016 = 100)
AG.SRF.TOTL.K2              Surface area (sq. km)
AG.YLD.CREL.KG              Cereal yield (kg per hectare)
BG.GSR.NFSV.GD.ZS           Trade in services (% of GDP)
BM.GSR.CMCP.ZS              Communications, computer, etc. (% of service imports, BoP)
BM.GSR.FCTY.CD              Primary income payments (BoP, current US$)
BM.GSR.GNFS.CD              Imports of goods and services (BoP, current US$)
BM.GSR.INSF.ZS              Insurance and financial services (% of service imports, BoP)
BM.GSR.MRCH.CD              Goods imports (BoP, current US$)
BM.GSR.NFSV.CD              Service imports (BoP, current US$)
BM.GSR.ROYL.CD              Charges for the use of intellectual property, payments (BoP, current US$)
BM.GSR.TOTL.CD              Imports of goods, services and primary income (BoP, current US$)
BM.GSR.TRAN.ZS              Transport services (% of service imports, BoP)
BM.GSR.TRVL.ZS              Travel services (% of service imports, BoP)
BM.KLT.DINV.CD.WD           Foreign direct investment, net outflows (BoP, current US$)
BM.KLT.DINV.WD.GD.ZS        Foreign direct investment, net outflows (% of GDP)
BM.TRF.PRVT.CD              Secondary income, other sectors, payments (BoP, current US$)
BM.TRF.PWKR.CD.DT           Personal remittances, paid (current US$)
BN.CAB.XOKA.CD              Current account balance (BoP, current US$)
BN.CAB.XOKA.GD.ZS           Current account balance (% of GDP)
BN.FIN.TOTL.CD              Net financial account (BoP, current US$)
BN.GSR.FCTY.CD              Net primary income (BoP, current US$)
BN.GSR.GNFS.CD              Net trade in goods and services (BoP, current US$)
BN.GSR.MRCH.CD              Net trade in goods (BoP, current US$)
BN.KAC.EOMS.CD              Net errors and omissions (BoP, current US$)
BN.KLT.DINV.CD              Foreign direct investment, net (BoP, current US$)
BN.KLT.PTXL.CD              Portfolio Investment, net (BoP, current US$)
BN.RES.INCL.CD              Reserves and related items (BoP, current US$)
BN.TRF.CURR.CD              Net secondary income (BoP, current US$)
BN.TRF.KOGT.CD              Net capital account (BoP, current US$)
BX.GRT.EXTA.CD.WD           Grants, excluding technical cooperation (BoP, current US$)
BX.GRT.TECH.CD.WD           Technical cooperation grants (BoP, current US$)
BX.GSR.CCIS.CD              ICT service exports (BoP, current US$)
BX.GSR.CCIS.ZS              ICT service exports (% of service exports, BoP)
BX.GSR.CMCP.ZS              Communications, computer, etc. (% of service exports, BoP)
BX.GSR.FCTY.CD              Primary income receipts (BoP, current US$)
BX.GSR.GNFS.CD              Exports of goods and services (BoP, current US$)
BX.GSR.INSF.ZS              Insurance and financial services (% of service exports, BoP)
BX.GSR.MRCH.CD              Goods exports (BoP, current US$)
BX.GSR.NFSV.CD              Service exports (BoP, current US$)
BX.GSR.ROYL.CD              Charges for the use of intellectual property, receipts (BoP, current US$)
BX.GSR.TOTL.CD              Exports of goods, services and primary income (BoP, current US$)
BX.GSR.TRAN.ZS              Transport services (% of service exports, BoP)
BX.GSR.TRVL.ZS              Travel services (% of service exports, BoP)
BX.KLT.DINV.CD.WD           Foreign direct investment, net inflows (BoP, current US$)
BX.KLT.DINV.WD.GD.ZS        Foreign direct investment, net inflows (% of GDP)
BX.PEF.TOTL.CD.WD           Portfolio equity, net inflows (BoP, current US$)
BX.TRF.CURR.CD              Secondary income receipts (BoP, current US$)
BX.TRF.PWKR.CD              Personal transfers, receipts (BoP, current US$)
BX.TRF.PWKR.CD.DT           Personal remittances, received (current US$)
BX.TRF.PWKR.DT.GD.ZS        Personal remittances, received (% of GDP)
CM.MKT.INDX.ZG              S&P Global Equity Indices (annual % change)
CM.MKT.LCAP.CD              Market capitalization of listed domestic companies (current US$)
CM.MKT.LCAP.GD.ZS           Market capitalization of listed domestic companies (% of GDP)
CM.MKT.LDOM.NO              Listed domestic companies, total
CM.MKT.TRAD.CD              Stocks traded, total value (current US$)
CM.MKT.TRAD.GD.ZS           Stocks traded, total value (% of GDP)
CM.MKT.TRNR                 Stocks traded, turnover ratio of domestic shares (%)
DC.DAC.AUSL.CD              Net bilateral aid flows from DAC donors, Australia (current US$)
DC.DAC.AUTL.CD              Net bilateral aid flows from DAC donors, Austria (current US$)
DC.DAC.BELL.CD              Net bilateral aid flows from DAC donors, Belgium (current US$)
DC.DAC.CANL.CD              Net bilateral aid flows from DAC donors, Canada (current US$)
DC.DAC.CECL.CD              Net bilateral aid flows from DAC donors, European Union institutions (current US$)
DC.DAC.CHEL.CD              Net bilateral aid flows from DAC donors, Switzerland (current US$)
DC.DAC.CZEL.CD              Net bilateral aid flows from DAC donors, Czechia (current US$)
DC.DAC.DEUL.CD              Net bilateral aid flows from DAC donors, Germany (current US$)
DC.DAC.DNKL.CD              Net bilateral aid flows from DAC donors, Denmark (current US$)
DC.DAC.ESPL.CD              Net bilateral aid flows from DAC donors, Spain (current US$)
DC.DAC.ESTL.CD              Net bilateral aid flows from DAC donors, Estonia (current US$)
DC.DAC.FINL.CD              Net bilateral aid flows from DAC donors, Finland (current US$)
DC.DAC.FRAL.CD              Net bilateral aid flows from DAC donors, France (current US$)
DC.DAC.GBRL.CD              Net bilateral aid flows from DAC donors, United Kingdom (current US$)
DC.DAC.GRCL.CD              Net bilateral aid flows from DAC donors, Greece (current US$)
DC.DAC.HUNL.CD              Net bilateral aid flows from DAC donors, Hungary (current US$)
DC.DAC.IRLL.CD              Net bilateral aid flows from DAC donors, Ireland (current US$)
DC.DAC.ISLL.CD              Net bilateral aid flows from DAC donors, Iceland (current US$)
DC.DAC.ITAL.CD              Net bilateral aid flows from DAC donors, Italy (current US$)
DC.DAC.JPNL.CD              Net bilateral aid flows from DAC donors, Japan (current US$)
DC.DAC.KORL.CD              Net bilateral aid flows from DAC donors, Korea, Rep. (current US$)
DC.DAC.LTUL.CD              Net bilateral aid flows from DAC donors, Lithuania (current US$)
DC.DAC.LUXL.CD              Net bilateral aid flows from DAC donors, Luxembourg (current US$)
DC.DAC.NLDL.CD              Net bilateral aid flows from DAC donors, Netherlands (current US$)
DC.DAC.NORL.CD              Net bilateral aid flows from DAC donors, Norway (current US$)
DC.DAC.NZLL.CD              Net bilateral aid flows from DAC donors, New Zealand (current US$)
DC.DAC.POLL.CD              Net bilateral aid flows from DAC donors, Poland (current US$)
DC.DAC.PRTL.CD              Net bilateral aid flows from DAC donors, Portugal (current US$)
DC.DAC.SVKL.CD              Net bilateral aid flows from DAC donors, Slovak Republic (current US$)
DC.DAC.SVNL.CD              Net bilateral aid flows from DAC donors, Slovenia (current US$)
DC.DAC.SWEL.CD              Net bilateral aid flows from DAC donors, Sweden (current US$)
DC.DAC.TOTL.CD              Net bilateral aid flows from DAC donors, Total (current US$)
DC.DAC.USAL.CD              Net bilateral aid flows from DAC donors, United States (current US$)
DC.ODA.TLDC.CD              Net ODA provided, to the least developed countries (current US$)
DC.ODA.TLDC.GN.ZS           Net ODA provided to the least developed countries (% of GNI)
DC.ODA.TOTL.CD              Net ODA provided, total (current US$)
DC.ODA.TOTL.GN.ZS           Net ODA provided, total (% of GNI)
DC.ODA.TOTL.KD              Net ODA provided, total (constant 2023 US$)
DT.DOD.DECT.CD              External debt stocks, total (DOD, current US$)
DT.DOD.DECT.GN.ZS           External debt stocks (% of GNI)
DT.DOD.DIMF.CD              Use of IMF credit (DOD, current US$)
DT.DOD.DLXF.CD              External debt stocks, long-term (DOD, current US$)
DT.DOD.DPNG.CD              External debt stocks, private nonguaranteed (PNG) (DOD, current US$)
DT.DOD.DPPG.CD              External debt stocks, public and publicly guaranteed (PPG) (DOD, current US$)
DT.DOD.DSTC.CD              External debt stocks, short-term (DOD, current US$)
DT.DOD.DSTC.IR.ZS           Short-term debt (% of total reserves)
DT.DOD.DSTC.XP.ZS           Short-term debt (% of exports of goods, services and primary income)
DT.DOD.DSTC.ZS              Short-term debt (% of total external debt)
DT.DOD.MIBR.CD              PPG, IBRD (DOD, current US$)
DT.DOD.MIDA.CD              PPG, IDA (DOD, current US$)
DT.DOD.MWBG.CD              IBRD loans and IDA credits (DOD, current US$)
DT.DOD.PVLX.CD              Present value of external debt (current US$)
DT.DOD.PVLX.EX.ZS           Present value of external debt (% of exports of goods, services and primary income)
DT.DOD.PVLX.GN.ZS           Present value of external debt (% of GNI)
DT.NFL.BLAT.CD              Net financial flows, bilateral (NFL, current US$)
DT.NFL.BOND.CD              Portfolio investment, bonds (PPG + PNG) (NFL, current US$)
DT.NFL.CERF.CD              Net official flows from UN agencies, CERF (current US$)
DT.NFL.DPNG.CD              Net flows on external debt, private nonguaranteed (PNG) (NFL, current US$)
DT.NFL.FAOG.CD              Net official flows from UN agencies, FAO (current US$)
DT.NFL.IAEA.CD              Net official flows from UN agencies, IAEA (current US$)
DT.NFL.IFAD.CD              Net official flows from UN agencies, IFAD (current US$)
DT.NFL.ILOG.CD              Net official flows from UN agencies, ILO (current US$)
DT.NFL.IMFC.CD              Net financial flows, IMF concessional (NFL, current US$)
DT.NFL.IMFN.CD              Net financial flows, IMF nonconcessional (NFL, current US$)
DT.NFL.MIBR.CD              Net financial flows, IBRD (NFL, current US$)
DT.NFL.MIDA.CD              Net financial flows, IDA (NFL, current US$)
DT.NFL.MLAT.CD              Net financial flows, multilateral (NFL, current US$)
DT.NFL.MOTH.CD              Net financial flows, others (NFL, current US$)
DT.NFL.NIFC.CD              IFC, private nonguaranteed (NFL, US$)
DT.NFL.OFFT.CD              PPG, official creditors (NFL, US$)
DT.NFL.PBND.CD              PPG, bonds (NFL, current US$)
DT.NFL.PCBK.CD              PPG, commercial banks (NFL, current US$)
DT.NFL.PCBO.CD              Commercial banks and other lending (PPG + PNG) (NFL, current US$)
DT.NFL.PNGB.CD              PNG, bonds (NFL, current US$)
DT.NFL.PNGC.CD              PNG, commercial banks and other creditors (NFL, current US$)
DT.NFL.PROP.CD              PPG, other private creditors (NFL, current US$)
DT.NFL.PRVT.CD              PPG, private creditors (NFL, US$)
DT.NFL.RDBC.CD              Net financial flows, RDB concessional (NFL, current US$)
DT.NFL.RDBN.CD              Net financial flows, RDB nonconcessional (NFL, current US$)
DT.NFL.SDGF.CD              Net official flows from UN agencies, SDGFUND (current US$)
DT.NFL.SPRP.CD              Net official flows from UN agencies, SPRP (current US$)
DT.NFL.UNAI.CD              Net official flows from UN agencies, UNAIDS (current US$)
DT.NFL.UNCD.CD              Net official flows from UN agencies, UNCDF (current US$)
DT.NFL.UNCF.CD              Net official flows from UN agencies, UNICEF (current US$)
DT.NFL.UNCR.CD              Net official flows from UN agencies, UNHCR (current US$)
DT.NFL.UNCTAD.CD            Net official flows from UN agencies, UNCTAD (current US$)
DT.NFL.UNCV.CD              Net official flows from UN agencies, UNCOVID (current US$)
DT.NFL.UNDP.CD              Net official flows from UN agencies, UNDP (current US$)
DT.NFL.UNEC.CD              Net official flows from UN agencies, UNECE (current US$)
DT.NFL.UNEP.CD              Net official flows from UN agencies, UNEP (current US$)
DT.NFL.UNFP.CD              Net official flows from UN agencies, UNFPA (current US$)
DT.NFL.UNID.CD              Net official flows from UN agencies, UNIDIR (current US$)
DT.NFL.UNIDO.CD             Net official flows from UN agencies, UNIDO (current US$)
DT.NFL.UNPB.CD              Net official flows from UN agencies, UNPBF (current US$)
DT.NFL.UNRW.CD              Net official flows from UN agencies, UNRWA (current US$)
DT.NFL.UNTA.CD              Net official flows from UN agencies, UNTA (current US$)
DT.NFL.UNWN.CD              Net official flows from UN agencies, UNWOMEN (current US$)
DT.NFL.UNWT.CD              Net official flows from UN agencies, UNWTO (current US$)
DT.NFL.WFPG.CD              Net official flows from UN agencies, WFP (current US$)
DT.NFL.WHOL.CD              Net official flows from UN agencies, WHO (current US$)
DT.NFL.WITC.CD              Net official flows from UN agencies, WTO-ITC (current US$)
DT.ODA.ALLD.CD              Net official development assistance and official aid received (current US$)
DT.ODA.ALLD.KD              Net official development assistance and official aid received (constant 2023 US$)
DT.ODA.OATL.CD              Net official aid received (current US$)
DT.ODA.OATL.KD              Net official aid received (constant 2023 US$)
DT.ODA.ODAT.CD              Net official development assistance received (current US$)
DT.ODA.ODAT.GI.ZS           Net ODA received (% of gross capital formation)
DT.ODA.ODAT.GN.ZS           Net ODA received (% of GNI)
DT.ODA.ODAT.KD              Net official development assistance received (constant 2023 US$)
DT.ODA.ODAT.MP.ZS           Net ODA received (% of imports of goods, services and primary income)
DT.ODA.ODAT.PC.ZS           Net ODA received per capita (current US$)
DT.ODA.ODAT.XP.ZS           Net ODA received (% of central government expense)
DT.TDS.DECT.CD              Debt service on external debt, total (TDS, current US$)
DT.TDS.DECT.EX.ZS           Total debt service (% of exports of goods, services and primary income)
DT.TDS.DECT.GN.ZS           Total debt service (% of GNI)
DT.TDS.DIMF.CD              IMF repurchases and charges (TDS, current US$)
DT.TDS.DPPF.XP.ZS           Debt service (PPG and IMF only, % of exports of goods, services and primary income)
DT.TDS.DPPG.CD              Debt service on external debt, public and publicly guaranteed (PPG) (TDS, current US$)
DT.TDS.DPPG.GN.ZS           Public and publicly guaranteed debt service (% of GNI)
DT.TDS.DPPG.XP.ZS           Public and publicly guaranteed debt service (% of exports of goods, services and primary income)
DT.TDS.MLAT.CD              Multilateral debt service (TDS, current US$)
DT.TDS.MLAT.PG.ZS           Multilateral debt service (% of public and publicly guaranteed debt service)
EG.CFT.ACCS.RU.ZS           Access to clean fuels and technologies for cooking, rural (% of rural population)
EG.CFT.ACCS.UR.ZS           Access to clean fuels and technologies for cooking, urban (% of urban population)
EG.CFT.ACCS.ZS              Access to clean fuels and technologies for cooking (% of population)
EG.EGY.PRIM.PP.KD           Energy intensity level of primary energy (MJ/$2021 PPP GDP)
EG.ELC.ACCS.RU.ZS           Access to electricity, rural (% of rural population)
EG.ELC.ACCS.UR.ZS           Access to electricity, urban (% of urban population)
EG.ELC.ACCS.ZS              Access to electricity (% of population)
EG.ELC.COAL.ZS              Electricity production from coal sources (% of total)
EG.ELC.FOSL.ZS              Electricity production from oil, gas and coal sources (% of total)
EG.ELC.HYRO.ZS              Electricity production from hydroelectric sources (% of total)
EG.ELC.LOSS.ZS              Electric power transmission and distribution losses (% of output)
EG.ELC.NGAS.ZS              Electricity production from natural gas sources (% of total)
EG.ELC.NUCL.ZS              Electricity production from nuclear sources (% of total)
EG.ELC.PETR.ZS              Electricity production from oil sources (% of total)
EG.ELC.RNEW.ZS              Renewable electricity output (% of total electricity output)
EG.ELC.RNWX.KH              Electricity production from renewable sources, excluding hydroelectric (kWh)
EG.ELC.RNWX.ZS              Electricity production from renewable sources, excluding hydroelectric (% of total)
EG.FEC.RNEW.ZS              Renewable energy consumption (% of total final energy consumption)
EG.GDP.PUSE.KO.PP           GDP per unit of energy use (PPP $ per kg of oil equivalent)
EG.GDP.PUSE.KO.PP.KD        GDP per unit of energy use (constant 2021 PPP $ per kg of oil equivalent)
EG.IMP.CONS.ZS              Energy imports, net (% of energy use)
EG.USE.COMM.CL.ZS           Alternative and nuclear energy (% of total energy use)
EG.USE.COMM.FO.ZS           Fossil fuel energy consumption (% of total)
EG.USE.COMM.GD.PP.KD        Energy use (kg of oil equivalent) per $1,000 GDP (constant 2021 PPP)
EG.USE.CRNW.ZS              Combustible renewables and waste (% of total energy)
EG.USE.ELEC.KH.PC           Electric power consumption (kWh per capita)
EG.USE.PCAP.KG.OE           Energy use (kg of oil equivalent per capita)
EN.ATM.PM25.MC.M3           PM2.5 air pollution, mean annual exposure (micrograms per cubic meter)
EN.ATM.PM25.MC.T1.ZS        PM2.5 pollution, population exposed to levels exceeding WHO Interim Target-1 value (% of total)
EN.ATM.PM25.MC.T2.ZS        PM2.5 pollution, population exposed to levels exceeding WHO Interim Target-2 value (% of total)
EN.ATM.PM25.MC.T3.ZS        PM2.5 pollution, population exposed to levels exceeding WHO Interim Target-3 value (% of total)
EN.ATM.PM25.MC.ZS           PM2.5 air pollution, population exposed to levels exceeding WHO guideline value (% of total)
EN.BIR.THRD.NO              Bird species, threatened
EN.CLC.DRSK.XQ              Disaster risk reduction progress score (1-5 scale; 5=best)
EN.CLC.MDAT.ZS              Droughts, floods, extreme temperatures (% of population, average 1990-2009)
EN.FSH.THRD.NO              Fish species, threatened
EN.GHG.ALL.LU.MT.CE.AR5     Total greenhouse gas emissions including LULUCF (Mt CO2e)

In [7]:
# Buscar los indicadores de interés en World Development Indicators
wbdata.get_indicators(query="GDP per capita", source=2)

id                 name
-----------------  -------------------------------------------------------------------
NY.GDP.PCAP.CD     GDP per capita (current US$)
NY.GDP.PCAP.CN     GDP per capita (current LCU)
NY.GDP.PCAP.KD     GDP per capita (constant 2015 US$)
NY.GDP.PCAP.KD.ZG  GDP per capita growth (annual %)
NY.GDP.PCAP.KN     GDP per capita (constant LCU)
NY.GDP.PCAP.PP.CD  GDP per capita, PPP (current international $)
NY.GDP.PCAP.PP.KD  GDP per capita, PPP (constant 2021 international $)
SE.XPD.PRIM.PC.ZS  Government expenditure per student, primary (% of GDP per capita)
SE.XPD.SECO.PC.ZS  Government expenditure per student, secondary (% of GDP per capita)
SE.XPD.TERT.PC.ZS  Government expenditure per student, tertiary (% of GDP per capita)

In [30]:
indicadores = {"NY.GDP.PCAP.PP.CD": "PIB per cápita (PPA, USD internacionales)",
               "SH.XPD.CHEX.PP.CD": "Gasto en salud per cápita (PPA, USD internacionales)",
               "SP.DYN.LE00.IN": "Esperanza de vida (años)",
               "SL.UEM.TOTL.NE.ZS": "Tasa de desempleo (%)"}

# Descargar datos para países de América del Sur de 2010 a 2022
df = wbdata.get_dataframe(indicadores, country=["COL", "PER", "BRA", "CHL", "ARG", "BOL", "ECU", "PRY", "URY"], date=("2010", "2022"))
df = df.reset_index()
df = df.rename(columns={'country': 'País', 'date': 'Año'})

In [ ]:
# Correr esto en caso de que no funcione la conexión a la API
# df = pd.read_csv("datos_banco_mundial.csv", converters={'Año': str})

## Exploración inicial del dataset

In [21]:
df

,País,Año,"PIB per cápita (PPA, USD internacionales)","Gasto en salud per cápita (PPA, USD internacionales)",Esperanza de vida (años),Tasa de desempleo (%)
0,Argentina,2022,"29,804.08","3,006.98",75.81,6.80
1,Argentina,2021,"26,300.27","2,895.42",73.95,8.74
2,Argentina,2020,"22,393.35","2,389.92",75.88,11.46
3,Argentina,2019,"23,516.83","2,379.69",76.85,9.84
4,Argentina,2018,"24,410.39","2,483.24",76.77,9.22
...,...,...,...,...,...,...
112,Uruguay,2014,"21,867.81","1,785.00",77.19,6.55
113,Uruguay,2013,"20,661.38","1,709.24",76.95,6.44
114,Uruguay,2012,"19,495.42","1,615.10",76.69,6.45
115,Uruguay,2011,"19,135.36","1,574.28",76.61,6.31
116,Uruguay,2010,"17,872.54","1,475.01",76.69,7.16

In [22]:
df.shape

(117, 6)

In [23]:
df.info()

<class 'wbdata.client.DataFrame'>
RangeIndex: 117 entries, 0 to 116
Data columns (total 6 columns):
 #   Column                                                Non-Null Count  Dtype
---  ------                                                --------------  -----
 0   País                                                  117 non-null    object
 1   Año                                                   117 non-null    object
 2   PIB per cápita (PPA, USD internacionales)             117 non-null    float64
 3   Gasto en salud per cápita (PPA, USD internacionales)  117 non-null    float64
 4   Esperanza de vida (años)                              117 non-null    float64
 5   Tasa de desempleo (%)                                 113 non-null    float64
dtypes: float64(4), object(2)
memory usage: 5.6+ KB

In [31]:
df["País"].value_counts(dropna=False)

País
Argentina    13
Bolivia      13
Brazil       13
Chile        13
Colombia     13
Ecuador      13
Peru         13
Paraguay     13
Uruguay      13
Name: count, dtype: int64

Tenemos una base de datos con información de 9 países de América del Sur para 13 años (2010-2022), lo que nos da un total de 117 filas. Se trajo información de 4 indicadores. La información se presenta en una estructura de panel de datos.

## Realizar filtros

En ocasiones, un economista quiere seleccionar subconjuntos de datos para analizar. Por ejemplo, podemos estar interesados en conocer cómo se comportaron los indicadores en los distintos países en el año 2022, por lo que vamos a crear un dataframe solo con la información de 2022.

In [32]:
df_2022 = df[df['Año']=="2022"]
df_2022

,País,Año,"PIB per cápita (PPA, USD internacionales)","Gasto en salud per cápita (PPA, USD internacionales)",Esperanza de vida (años),Tasa de desempleo (%)
0,Argentina,2022,"29,804.08","3,006.98",75.81,6.80
13,Bolivia,2022,"12,304.78",742.56,67.43,3.45
26,Brazil,2022,"19,873.70","1,865.92",74.87,9.23
39,Chile,2022,"30,918.93","3,083.67",79.18,8.33
52,Colombia,2022,"20,854.00","1,570.88",76.51,10.54
65,Ecuador,2022,"15,195.66","1,157.05",76.58,3.67
78,Peru,2022,"16,673.69","1,006.93",76.83,4.00
91,Paraguay,2022,"16,305.62","1,264.51",72.32,6.76
104,Uruguay,2022,"33,033.57","2,959.25",76.47,7.88

In [33]:
# Reiniciamos el índice
df_2022.reset_index(drop=True, inplace=True)
df_2022

,País,Año,"PIB per cápita (PPA, USD internacionales)","Gasto en salud per cápita (PPA, USD internacionales)",Esperanza de vida (años),Tasa de desempleo (%)
0,Argentina,2022,"29,804.08","3,006.98",75.81,6.80
1,Bolivia,2022,"12,304.78",742.56,67.43,3.45
2,Brazil,2022,"19,873.70","1,865.92",74.87,9.23
3,Chile,2022,"30,918.93","3,083.67",79.18,8.33
4,Colombia,2022,"20,854.00","1,570.88",76.51,10.54
5,Ecuador,2022,"15,195.66","1,157.05",76.58,3.67
6,Peru,2022,"16,673.69","1,006.93",76.83,4.00
7,Paraguay,2022,"16,305.62","1,264.51",72.32,6.76
8,Uruguay,2022,"33,033.57","2,959.25",76.47,7.88

### Filtrar por el índice

Queremos ver la información correspondiente al índice 3 y 4

In [34]:
df_2022.iloc[3:5][['País','PIB per cápita (PPA, USD internacionales)']]

       País  PIB per cápita (PPA, USD internacionales)
3     Chile                                  30,918.93
4  Colombia                                  20,854.00

In [35]:
df_2022[['País','PIB per cápita (PPA, USD internacionales)']]

        País  PIB per cápita (PPA, USD internacionales)
0  Argentina                                  29,804.08
1    Bolivia                                  12,304.78
2     Brazil                                  19,873.70
3      Chile                                  30,918.93
4   Colombia                                  20,854.00
5    Ecuador                                  15,195.66
6       Peru                                  16,673.69
7   Paraguay                                  16,305.62
8    Uruguay                                  33,033.57

### Filtrar por una columna

Queremos ver la información de Colombia

In [40]:
df_2022[df_2022['País']=="Colombia"]

,País,Año,"PIB per cápita (PPA, USD internacionales)","Gasto en salud per cápita (PPA, USD internacionales)",Esperanza de vida (años),Tasa de desempleo (%)
4,Colombia,2022,"20,854.00","1,570.88",76.51,10.54

**Ejercicio**

Muéstrame todos los países que sean diferentes a Colombia

In [41]:
df_2022[df_2022['País']!="Colombia"]

,País,Año,"PIB per cápita (PPA, USD internacionales)","Gasto en salud per cápita (PPA, USD internacionales)",Esperanza de vida (años),Tasa de desempleo (%)
0,Argentina,2022,"29,804.08","3,006.98",75.81,6.80
1,Bolivia,2022,"12,304.78",742.56,67.43,3.45
2,Brazil,2022,"19,873.70","1,865.92",74.87,9.23
3,Chile,2022,"30,918.93","3,083.67",79.18,8.33
5,Ecuador,2022,"15,195.66","1,157.05",76.58,3.67
6,Peru,2022,"16,673.69","1,006.93",76.83,4.00
7,Paraguay,2022,"16,305.62","1,264.51",72.32,6.76
8,Uruguay,2022,"33,033.57","2,959.25",76.47,7.88

**Ejercicio**

¿Qué países tienen una tasa de desempleo menor estrictamente a 5%?

In [44]:
df_2022[df_2022['Tasa de desempleo (%)']<5]

,País,Año,"PIB per cápita (PPA, USD internacionales)","Gasto en salud per cápita (PPA, USD internacionales)",Esperanza de vida (años),Tasa de desempleo (%)
1,Bolivia,2022,"12,304.78",742.56,67.43,3.45
5,Ecuador,2022,"15,195.66","1,157.05",76.58,3.67
6,Peru,2022,"16,673.69","1,006.93",76.83,4.00

### Filtrar por varias columnas

¿Qué países tienen una tasa de desempleo mayor o igual a 6% y una esperanza de vida mayor o igual a 75 años?

In [50]:
df_2022[(df_2022['Tasa de desempleo (%)']>=6)&(df_2022['Esperanza de vida (años)']>=75)]

,País,Año,"PIB per cápita (PPA, USD internacionales)","Gasto en salud per cápita (PPA, USD internacionales)",Esperanza de vida (años),Tasa de desempleo (%)
0,Argentina,2022,"29,804.08","3,006.98",75.81,6.80
3,Chile,2022,"30,918.93","3,083.67",79.18,8.33
4,Colombia,2022,"20,854.00","1,570.88",76.51,10.54
8,Uruguay,2022,"33,033.57","2,959.25",76.47,7.88

¿Qué países tienen un PIB per cápita PPA mayor a USD 25.000 o un gasto en salud per cápita PPA mayor a USD 1.000?

In [51]:
df_2022[(df_2022['PIB per cápita (PPA, USD internacionales)']>25000) | (df_2022['Gasto en salud per cápita (PPA, USD internacionales)']>1000)]

,País,Año,"PIB per cápita (PPA, USD internacionales)","Gasto en salud per cápita (PPA, USD internacionales)",Esperanza de vida (años),Tasa de desempleo (%)
0,Argentina,2022,"29,804.08","3,006.98",75.81,6.80
2,Brazil,2022,"19,873.70","1,865.92",74.87,9.23
3,Chile,2022,"30,918.93","3,083.67",79.18,8.33
4,Colombia,2022,"20,854.00","1,570.88",76.51,10.54
5,Ecuador,2022,"15,195.66","1,157.05",76.58,3.67
6,Peru,2022,"16,673.69","1,006.93",76.83,4.00
7,Paraguay,2022,"16,305.62","1,264.51",72.32,6.76
8,Uruguay,2022,"33,033.57","2,959.25",76.47,7.88

### Filtrar por el mínimo o máximo de una columna

¿Cuál país tiene el PIB per cápita más alto?

In [52]:
df_2022[df_2022['PIB per cápita (PPA, USD internacionales)'] == df_2022['PIB per cápita (PPA, USD internacionales)'].max()]

,País,Año,"PIB per cápita (PPA, USD internacionales)","Gasto en salud per cápita (PPA, USD internacionales)",Esperanza de vida (años),Tasa de desempleo (%)
8,Uruguay,2022,"33,033.57","2,959.25",76.47,7.88

**Ejercicio**

¿Cuál país tiene la esperanza de vida más baja?

In [55]:
df_2022[df_2022['Esperanza de vida (años)']==df_2022['Esperanza de vida (años)'].min()]

,País,Año,"PIB per cápita (PPA, USD internacionales)","Gasto en salud per cápita (PPA, USD internacionales)",Esperanza de vida (años),Tasa de desempleo (%)
1,Bolivia,2022,"12,304.78",742.56,67.43,3.45

**Ejercicio**

¿Qué países tienen un gasto en salud per cápita PPA por encima del promedio?

.mean()

In [56]:
df_2022[df_2022['Gasto en salud per cápita (PPA, USD internacionales)']>df_2022['Gasto en salud per cápita (PPA, USD internacionales)'].mean()]

,País,Año,"PIB per cápita (PPA, USD internacionales)","Gasto en salud per cápita (PPA, USD internacionales)",Esperanza de vida (años),Tasa de desempleo (%)
0,Argentina,2022,"29,804.08","3,006.98",75.81,6.80
2,Brazil,2022,"19,873.70","1,865.92",74.87,9.23
3,Chile,2022,"30,918.93","3,083.67",79.18,8.33
8,Uruguay,2022,"33,033.57","2,959.25",76.47,7.88

### Filtrar por una lista de valores

Muéstrame los datos para Brasil y Ecuador

In [57]:
df_2022[df_2022['País'].isin(['Brazil', 'Ecuador'])]

,País,Año,"PIB per cápita (PPA, USD internacionales)","Gasto en salud per cápita (PPA, USD internacionales)",Esperanza de vida (años),Tasa de desempleo (%)
2,Brazil,2022,"19,873.70","1,865.92",74.87,9.23
5,Ecuador,2022,"15,195.66","1,157.05",76.58,3.67

### Filtrar los strings que contengan ciertos caracteres

Muéstrame los países que contengan "P"

In [60]:
df_2022[df_2022['País'].str.contains('P', na=False)]

,País,Año,"PIB per cápita (PPA, USD internacionales)","Gasto en salud per cápita (PPA, USD internacionales)",Esperanza de vida (años),Tasa de desempleo (%)
6,Peru,2022,"16,673.69","1,006.93",76.83,4.00
7,Paraguay,2022,"16,305.62","1,264.51",72.32,6.76

Muéstrame los países que contengan "Pe" o "Br" o "Ch"

In [61]:
df_2022[df_2022['País'].str.contains(r'Pe|Br|Ch', na=False)]

,País,Año,"PIB per cápita (PPA, USD internacionales)","Gasto en salud per cápita (PPA, USD internacionales)",Esperanza de vida (años),Tasa de desempleo (%)
2,Brazil,2022,"19,873.70","1,865.92",74.87,9.23
3,Chile,2022,"30,918.93","3,083.67",79.18,8.33
6,Peru,2022,"16,673.69","1,006.93",76.83,4.00

**Ejercicio**

Muestra los países que contengan "guay"

In [62]:
df_2022[df_2022['País'].str.contains('guay', na=False)]

,País,Año,"PIB per cápita (PPA, USD internacionales)","Gasto en salud per cápita (PPA, USD internacionales)",Esperanza de vida (años),Tasa de desempleo (%)
7,Paraguay,2022,"16,305.62","1,264.51",72.32,6.76
8,Uruguay,2022,"33,033.57","2,959.25",76.47,7.88

### Filtrar por negación (todo excepto ...)

Muéstrame todos los países excepto Brasil

In [63]:
df_2022[~(df_2022['País']=='Brazil')]

,País,Año,"PIB per cápita (PPA, USD internacionales)","Gasto en salud per cápita (PPA, USD internacionales)",Esperanza de vida (años),Tasa de desempleo (%)
0,Argentina,2022,"29,804.08","3,006.98",75.81,6.80
1,Bolivia,2022,"12,304.78",742.56,67.43,3.45
3,Chile,2022,"30,918.93","3,083.67",79.18,8.33
4,Colombia,2022,"20,854.00","1,570.88",76.51,10.54
5,Ecuador,2022,"15,195.66","1,157.05",76.58,3.67
6,Peru,2022,"16,673.69","1,006.93",76.83,4.00
7,Paraguay,2022,"16,305.62","1,264.51",72.32,6.76
8,Uruguay,2022,"33,033.57","2,959.25",76.47,7.88

**Ejercicio**

Muéstrame todos los países excepto los que terminan en "guay". Filtra utilizando negación.

In [69]:
df_2022[~df_2022['País'].str.endswith('guay')]

,País,Año,"PIB per cápita (PPA, USD internacionales)","Gasto en salud per cápita (PPA, USD internacionales)",Esperanza de vida (años),Tasa de desempleo (%)
0,Argentina,2022,"29,804.08","3,006.98",75.81,6.80
1,Bolivia,2022,"12,304.78",742.56,67.43,3.45
2,Brazil,2022,"19,873.70","1,865.92",74.87,9.23
3,Chile,2022,"30,918.93","3,083.67",79.18,8.33
4,Colombia,2022,"20,854.00","1,570.88",76.51,10.54
5,Ecuador,2022,"15,195.66","1,157.05",76.58,3.67
6,Peru,2022,"16,673.69","1,006.93",76.83,4.00

**Ejercicio**

Muestra los países donde su PIB per cápita no sea mayor a USD 25.000 PPA y su tasa de desempleo no sea menor a 5%. Filtra utilizando negación.

In [70]:
df_2022[~(df_2022['PIB per cápita (PPA, USD internacionales)']>25000)&~(df_2022['Tasa de desempleo (%)']<5)]

,País,Año,"PIB per cápita (PPA, USD internacionales)","Gasto en salud per cápita (PPA, USD internacionales)",Esperanza de vida (años),Tasa de desempleo (%)
2,Brazil,2022,"19,873.70","1,865.92",74.87,9.23
4,Colombia,2022,"20,854.00","1,570.88",76.51,10.54
7,Paraguay,2022,"16,305.62","1,264.51",72.32,6.76

## Ordenar el dataframe

Para un economista, ordenar es sinónimo de ranking. ¿Qué país tiene el mayor PIB? ¿Cuál tiene la menor tasa de inflación? sort_values() nos permite responder a estas preguntas.

### Ordenar según el valor de una columna

Vamos a ordenar los países de menor a mayor gasto en salud per cápita

In [71]:
df_2022.sort_values(by=['Gasto en salud per cápita (PPA, USD internacionales)'], ascending = True)

,País,Año,"PIB per cápita (PPA, USD internacionales)","Gasto en salud per cápita (PPA, USD internacionales)",Esperanza de vida (años),Tasa de desempleo (%)
1,Bolivia,2022,"12,304.78",742.56,67.43,3.45
6,Peru,2022,"16,673.69","1,006.93",76.83,4.00
5,Ecuador,2022,"15,195.66","1,157.05",76.58,3.67
7,Paraguay,2022,"16,305.62","1,264.51",72.32,6.76
4,Colombia,2022,"20,854.00","1,570.88",76.51,10.54
2,Brazil,2022,"19,873.70","1,865.92",74.87,9.23
8,Uruguay,2022,"33,033.57","2,959.25",76.47,7.88
0,Argentina,2022,"29,804.08","3,006.98",75.81,6.80
3,Chile,2022,"30,918.93","3,083.67",79.18,8.33

**Ejercicio**

Ordena los países de mayor a menor PIB per cápita PPA

In [73]:
df_2022.sort_values(by=['PIB per cápita (PPA, USD internacionales)'], ascending=False)

,País,Año,"PIB per cápita (PPA, USD internacionales)","Gasto en salud per cápita (PPA, USD internacionales)",Esperanza de vida (años),Tasa de desempleo (%)
8,Uruguay,2022,"33,033.57","2,959.25",76.47,7.88
3,Chile,2022,"30,918.93","3,083.67",79.18,8.33
0,Argentina,2022,"29,804.08","3,006.98",75.81,6.80
4,Colombia,2022,"20,854.00","1,570.88",76.51,10.54
2,Brazil,2022,"19,873.70","1,865.92",74.87,9.23
6,Peru,2022,"16,673.69","1,006.93",76.83,4.00
7,Paraguay,2022,"16,305.62","1,264.51",72.32,6.76
5,Ecuador,2022,"15,195.66","1,157.05",76.58,3.67
1,Bolivia,2022,"12,304.78",742.56,67.43,3.45

**Ejercicio**

 Encuentra los 5 países con la menor tasa de desempleo en 2022.

In [74]:
df_2022.sort_values(by=['Tasa de desempleo (%)'], ascending=True).head()

,País,Año,"PIB per cápita (PPA, USD internacionales)","Gasto en salud per cápita (PPA, USD internacionales)",Esperanza de vida (años),Tasa de desempleo (%)
1,Bolivia,2022,"12,304.78",742.56,67.43,3.45
5,Ecuador,2022,"15,195.66","1,157.05",76.58,3.67
6,Peru,2022,"16,673.69","1,006.93",76.83,4.00
7,Paraguay,2022,"16,305.62","1,264.51",72.32,6.76
0,Argentina,2022,"29,804.08","3,006.98",75.81,6.80

### Ordenar según el valor de varias columnas

In [75]:
# Datos económicos sintéticos de varios países
datos = {
    'País': ['Colombia', 'Chile', 'México', 'Argentina', 'Perú', 'Panamá'],
    'Región': ['Andina', 'Andina', 'Norteamérica', 'Sur', 'Andina', 'Centroamérica'],
    'Crecimiento_PIB_%': [1.5, 2.1, 2.5, -1.1, 2.8, 4.1],
    'Tasa_Desempleo_%': [10.5, 8.8, 3.5, 11.2, 7.5, 8.1]
}

# Creamos el DataFrame
df_ejemplo = pd.DataFrame(datos)

df_ejemplo

        País         Región  Crecimiento_PIB_%  Tasa_Desempleo_%
0   Colombia         Andina               1.50             10.50
1      Chile         Andina               2.10              8.80
2     México   Norteamérica               2.50              3.50
3  Argentina            Sur              -1.10             11.20
4       Perú         Andina               2.80              7.50
5     Panamá  Centroamérica               4.10              8.10

In [77]:
df_ordenado = df_ejemplo.sort_values(by=['Región', 'Crecimiento_PIB_%'], ascending=[True, False])
df_ordenado

        País         Región  Crecimiento_PIB_%  Tasa_Desempleo_%
4       Perú         Andina               2.80              7.50
1      Chile         Andina               2.10              8.80
0   Colombia         Andina               1.50             10.50
5     Panamá  Centroamérica               4.10              8.10
2     México   Norteamérica               2.50              3.50
3  Argentina            Sur              -1.10             11.20

## Groupby

Esta es una de las herramientas más utilizadas, ya que permite agrupar por categorías y sacar mediciones para cada grupo como la media, la suma, la desviación estándar, el conteo de registros, etc.

Para ello, se emplea la estrategia de Dividir-Aplicar-Combinar.

- **Dividir (Split):** Se separa el DataFrame en grupos basados en una o más variables categóricas (ejemplo: País, Año, etc).

- **Aplicar (Apply):** A cada grupo se le aplica una función (ejemplo: mean, sum, std).

- **Combinar (Combine):** Se juntan los resultados en un nuevo DataFrame.

Es como si el FMI quisiera calcular la tasa de inflación promedio para cada continente. Primero, divide el dataset global por continente. Luego, aplica la función de promedio a la columna de inflación para cada grupo. Finalmente, combina los resultados en una tabla resumen.

In [78]:
# Dataframe original
df

,País,Año,"PIB per cápita (PPA, USD internacionales)","Gasto en salud per cápita (PPA, USD internacionales)",Esperanza de vida (años),Tasa de desempleo (%)
0,Argentina,2022,"29,804.08","3,006.98",75.81,6.80
1,Argentina,2021,"26,300.27","2,895.42",73.95,8.74
2,Argentina,2020,"22,393.35","2,389.92",75.88,11.46
3,Argentina,2019,"23,516.83","2,379.69",76.85,9.84
4,Argentina,2018,"24,410.39","2,483.24",76.77,9.22
...,...,...,...,...,...,...
112,Uruguay,2014,"21,867.81","1,785.00",77.19,6.55
113,Uruguay,2013,"20,661.38","1,709.24",76.95,6.44
114,Uruguay,2012,"19,495.42","1,615.10",76.69,6.45
115,Uruguay,2011,"19,135.36","1,574.28",76.61,6.31
116,Uruguay,2010,"17,872.54","1,475.01",76.69,7.16

¿Cuál fue la esperanza de vida promedio de cada país entre 2010 y 2022?

In [79]:
df.groupby('País')['Esperanza de vida (años)'].mean()

País
Argentina   76.01
Bolivia     66.31
Brazil      74.69
Chile       79.69
Colombia    75.65
Ecuador     75.56
Paraguay    72.77
Peru        74.79
Uruguay     77.05
Name: Esperanza de vida (años), dtype: float64

In [80]:
df.groupby('País')['Esperanza de vida (años)'].mean().reset_index()

        País  Esperanza de vida (años)
0  Argentina                     76.01
1    Bolivia                     66.31
2     Brazil                     74.69
3      Chile                     79.69
4   Colombia                     75.65
5    Ecuador                     75.56
6   Paraguay                     72.77
7       Peru                     74.79
8    Uruguay                     77.05

Ordenemos de mayor a menor...

In [85]:
df.groupby('País')['Esperanza de vida (años)'].mean().reset_index().sort_values(by='Esperanza de vida (años)', ascending=False)

        País  Esperanza de vida (años)
3      Chile                     79.69
8    Uruguay                     77.05
0  Argentina                     76.01
4   Colombia                     75.65
5    Ecuador                     75.56
7       Peru                     74.79
2     Brazil                     74.69
6   Paraguay                     72.77
1    Bolivia                     66.31

¿Cuál fue la tasa de desempleo más baja que registró cada país entre 2010 y 2022?

In [81]:
df.groupby('País')['Tasa de desempleo (%)'].min().reset_index()

        País  Tasa de desempleo (%)
0  Argentina                   6.80
1    Bolivia                   2.02
2     Brazil                   6.75
3      Chile                   6.36
4   Colombia                   8.57
5    Ecuador                   2.91
6   Paraguay                   4.08
7       Peru                   3.21
8    Uruguay                   6.31

¿Cuánto sumó el gasto en salud per cápita de estos países en cada uno de los años de estudio (2010-2022)?

In [87]:
df.groupby('País')['Gasto en salud per cápita (PPA, USD internacionales)'].sum().reset_index()

        País  Gasto en salud per cápita (PPA, USD internacionales)
0  Argentina                                          28,937.47
1    Bolivia                                           6,574.41
2     Brazil                                          18,269.10
3      Chile                                          26,663.17
4   Colombia                                          14,314.92
5    Ecuador                                          11,258.45
6   Paraguay                                          11,777.79
7       Peru                                           8,592.91
8    Uruguay                                          26,509.17

Para cada país de América del Sur, ¿cuál fue el promedio de PIB per cápita PPA y de gasto en salud per cápita PPA entre 2010 y 2022?

In [88]:
df.groupby("País")[["PIB per cápita (PPA, USD internacionales)","Gasto en salud per cápita (PPA, USD internacionales)"]].mean().reset_index()

,País,"PIB per cápita (PPA, USD internacionales)","Gasto en salud per cápita (PPA, USD internacionales)"
0,Argentina,"21,970.33","2,225.96"
1,Bolivia,"9,230.50",505.72
2,Brazil,"15,821.96","1,405.32"
3,Chile,"23,883.23","2,051.01"
4,Colombia,"14,439.52","1,101.15"
5,Ecuador,"11,586.61",866.03
6,Paraguay,"13,255.63",905.98
7,Peru,"12,397.29",660.99
8,Uruguay,"23,539.09","2,039.17"

Para cada país de América del Sur, ¿cuál fue el promedio de gasto en salud per cápita PPA y cuál fue la máxima esperanza de vida entre 2010 y 2022?

In [90]:
df.groupby("País")[["Gasto en salud per cápita (PPA, USD internacionales)","Esperanza de vida (años)"]].agg(["mean", "max"]).reset_index()

        País Gasto en salud per cápita (PPA, USD internacionales)           \
                                                             mean      max
0  Argentina                                           2,225.96   3,006.98
1    Bolivia                                             505.72     771.48
2     Brazil                                           1,405.32   1,865.92
3      Chile                                           2,051.01   3,083.67
4   Colombia                                           1,101.15   1,589.08
5    Ecuador                                             866.03   1,157.05
6   Paraguay                                             905.98   1,264.51
7       Peru                                             660.99   1,019.32
8    Uruguay                                           2,039.17   2,959.25

  Esperanza de vida (años)
                      mean   max
0                    76.01 76.85
1                    66.31 67.82
2                    74.69 75.81
3                    79.69 80.61
4                    75.65 76.79
5                    75.56 77.29
6                    72.77 73.67
7                    74.79 76.83
8                    77.05 78.38

In [93]:
df.groupby("País", as_index=False).agg(
    gasto_promedio_salud=("Gasto en salud per cápita (PPA, USD internacionales)", "mean"),
    max_esperanza_vida=("Esperanza de vida (años)", "max")
)

        País  gasto_promedio_salud  max_esperanza_vida
0  Argentina              2,225.96               76.85
1    Bolivia                505.72               67.82
2     Brazil              1,405.32               75.81
3      Chile              2,051.01               80.61
4   Colombia              1,101.15               76.79
5    Ecuador                866.03               77.29
6   Paraguay                905.98               73.67
7       Peru                660.99               76.83
8    Uruguay              2,039.17               78.38

Para cada país de América del Sur, calcule el mínimo, el máximo y el promedio del gasto en salud per cápita PPA y de la esperanza de vida entre 2010 y 2022

In [94]:
df.groupby("País")[["Gasto en salud per cápita (PPA, USD internacionales)","Esperanza de vida (años)"]].agg(["min", "mean", "max"]).reset_index()

        País Gasto en salud per cápita (PPA, USD internacionales)           \
                                                              min     mean
0  Argentina                                           1,692.89   2,225.96
1    Bolivia                                             265.35     505.72
2     Brazil                                           1,148.21   1,405.32
3      Chile                                           1,221.93   2,051.01
4   Colombia                                             758.86   1,101.15
5    Ecuador                                             569.46     866.03
6   Paraguay                                             595.42     905.98
7       Peru                                             462.36     660.99
8    Uruguay                                           1,475.01   2,039.17

           Esperanza de vida (años)
       max                      min  mean   max
0 3,006.98                    73.95 76.01 76.85
1   771.48                    61.43 66.31 67.82
2 1,865.92                    73.04 74.69 75.81
3 3,083.67                    78.88 79.69 80.61
4 1,589.08                    72.70 75.65 76.79
5 1,157.05                    72.00 75.56 77.29
6 1,264.51                    68.11 72.77 73.67
7 1,019.32                    71.60 74.79 76.83
8 2,959.25                    75.43 77.05 78.38

**Ejercicio**

Para cada país de América del Sur, calcule la mediana y la desviación estándar del PIB per cápita PPA entre 2010 y 2022

In [98]:
df.groupby("País")["PIB per cápita (PPA, USD internacionales)"].agg(["median", "std"]).reset_index()

        País    median      std
0  Argentina 20,105.76 3,420.51
1    Bolivia  9,242.03 1,878.14
2     Brazil 15,463.74 1,562.51
3      Chile 23,256.50 3,502.45
4   Colombia 14,026.84 2,675.46
5    Ecuador 11,526.80 1,610.92
6   Paraguay 13,329.14 1,665.61
7       Peru 12,066.55 1,934.33
8    Uruguay 22,840.55 4,249.51

## Tablas pivote o dinámicas

Una tabla pivote es una forma avanzada de groupby que nos **permite remodelar el DataFrame**, poniendo una variable categórica como índice, otra como columnas y una variable numérica como los valores. **Es similar a las tablas dinámicas en Excel.**

Por ejemplo, creemos una tabla para un informe donde las filas son los países, las columnas son los años (2010, 2011, 2012...), y los valores en las celdas son la tasa de desempleo. Esto facilita enormemente la comparación de la evolución del desempleo entre países.

In [99]:
df

,País,Año,"PIB per cápita (PPA, USD internacionales)","Gasto en salud per cápita (PPA, USD internacionales)",Esperanza de vida (años),Tasa de desempleo (%)
0,Argentina,2022,"29,804.08","3,006.98",75.81,6.80
1,Argentina,2021,"26,300.27","2,895.42",73.95,8.74
2,Argentina,2020,"22,393.35","2,389.92",75.88,11.46
3,Argentina,2019,"23,516.83","2,379.69",76.85,9.84
4,Argentina,2018,"24,410.39","2,483.24",76.77,9.22
...,...,...,...,...,...,...
112,Uruguay,2014,"21,867.81","1,785.00",77.19,6.55
113,Uruguay,2013,"20,661.38","1,709.24",76.95,6.44
114,Uruguay,2012,"19,495.42","1,615.10",76.69,6.45
115,Uruguay,2011,"19,135.36","1,574.28",76.61,6.31
116,Uruguay,2010,"17,872.54","1,475.01",76.69,7.16

In [102]:
df_desempleo = df.pivot(index='País', columns='Año', values='Tasa de desempleo (%)').reset_index()
df_desempleo

Año,País,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Argentina,7.71,7.18,7.22,7.10,7.27,NaN,NaN,8.35,9.22,9.84,11.46,8.74,6.80
1,Bolivia,NaN,2.25,2.07,2.44,2.02,3.11,3.50,3.65,3.52,3.68,7.90,4.94,3.45
2,Brazil,NaN,7.58,7.25,7.07,6.75,8.54,11.58,12.79,12.33,11.94,13.70,13.16,9.23
3,Chile,8.55,7.49,6.79,6.36,6.76,6.61,6.93,7.30,7.67,7.56,11.18,9.42,8.33
4,Colombia,11.15,10.29,9.96,9.25,8.80,8.57,8.92,9.09,9.36,10.28,15.57,13.90,10.54
5,Ecuador,4.09,3.46,3.23,2.91,3.28,3.42,4.39,3.71,3.40,3.70,6.08,4.43,3.67
6,Paraguay,4.57,4.67,4.08,4.38,5.03,4.56,5.25,6.14,6.22,6.59,7.55,7.33,6.76
7,Peru,3.60,3.48,3.24,3.58,3.21,3.27,3.74,3.69,3.49,3.38,7.18,5.10,4.00
8,Uruguay,7.16,6.31,6.45,6.44,6.55,7.49,7.84,7.89,8.34,8.84,10.41,9.33,7.88

Este formato **ancho (wide)** es muy intuitivo. Podemos comparar fácilmente el desempleo en 2022 de los diferentes países de América del Sur y ver que el de Colombia es el más alto.

También podemos seguir la fila de un país para ver su tendencia, como por ejemplo, ver el comportamiento que ha tenido la tasa de desempleo de Colombia entre 2010 y 2022 y ver que durante la pandemia llegó a un máximo de 16%.

A continuación, vamos a crear una tabla que presenta, para cada país, la evolución 2010-2022 del PIB per cápita PPA y de la tasa de desempleo.

In [103]:
df1 = pd.pivot_table(df, index = 'País', columns = 'Año',
                     values = ['PIB per cápita (PPA, USD internacionales)',
                               'Tasa de desempleo (%)']).reset_index()
df1

          País PIB per cápita (PPA, USD internacionales)                      \
Año                                                 2010      2011      2012
0    Argentina                                 17,847.61 19,104.99 19,430.42
1      Bolivia                                  6,245.34  6,597.96  7,183.83
2       Brazil                                 14,451.72 15,211.79 15,198.09
3        Chile                                 17,917.90 20,121.68 21,366.18
4     Colombia                                 10,841.13 11,707.46 12,093.08
5      Ecuador                                  8,968.94  9,768.69 10,244.52
6     Paraguay                                 10,893.31 11,441.76 10,954.33
7         Peru                                  9,713.36 10,462.58 10,757.15
8      Uruguay                                 17,872.54 19,135.36 19,495.42

                                                                           \
Año      2013      2014      2015      2016      2017      2018      2019
0   19,928.99 19,487.42 19,899.15 20,105.76 23,385.07 24,410.39 23,516.83
1    8,068.72  8,628.94  8,757.32  9,242.03 10,420.39 10,758.41 11,005.35
2   15,722.33 15,827.31 14,821.44 14,309.21 14,559.05 15,463.74 16,069.84
3   22,201.07 22,553.62 22,468.31 23,256.50 24,295.22 25,305.09 25,613.91
4   12,779.89 13,355.36 13,332.06 14,026.84 14,400.61 15,239.40 16,181.59
5   11,295.61 11,835.61 10,877.75 10,881.49 11,793.48 12,186.88 12,543.01
6   12,137.01 12,607.07 12,679.06 13,329.14 13,977.34 14,139.09 14,149.60
7   11,290.55 11,517.74 11,600.39 12,066.55 12,591.86 13,078.23 13,563.54
8   20,661.38 21,867.81 22,168.61 22,840.55 23,606.64 24,386.49 25,782.69

                                  Tasa de desempleo (%)                       \
Año      2020      2021      2022                  2010  2011 2012 2013 2014
0   22,393.35 26,300.27 29,804.08                  7.71  7.18 7.22 7.10 7.27
1    9,580.99 11,202.44 12,304.78                   NaN  2.25 2.07 2.44 2.02
2   16,101.62 18,075.71 19,873.70                   NaN  7.58 7.25 7.07 6.75
3   25,357.01 29,106.64 30,918.93                  8.55  7.49 6.79 6.36 6.76
4   15,519.21 17,383.09 20,854.00                 11.15 10.29 9.96 9.25 8.80
5   11,526.80 13,507.44 15,195.66                  4.09  3.46 3.23 2.91 3.28
6   14,308.88 15,400.94 16,305.62                  4.57  4.67 4.08 4.38 5.03
7   12,563.30 15,285.77 16,673.69                  3.60  3.48 3.24 3.58 3.21
8   25,725.26 29,431.87 33,033.57                  7.16  6.31 6.45 6.44 6.55


Año 2015  2016  2017  2018  2019  2020  2021  2022
0    NaN   NaN  8.35  9.22  9.84 11.46  8.74  6.80
1   3.11  3.50  3.65  3.52  3.68  7.90  4.94  3.45
2   8.54 11.58 12.79 12.33 11.94 13.70 13.16  9.23
3   6.61  6.93  7.30  7.67  7.56 11.18  9.42  8.33
4   8.57  8.92  9.09  9.36 10.28 15.57 13.90 10.54
5   3.42  4.39  3.71  3.40  3.70  6.08  4.43  3.67
6   4.56  5.25  6.14  6.22  6.59  7.55  7.33  6.76
7   3.27  3.74  3.69  3.49  3.38  7.18  5.10  4.00
8   7.49  7.84  7.89  8.34  8.84 10.41  9.33  7.88

En la siguiente tabla, vamos a mostrar, para cada país, el valor promedio del PIB per cápita PPA y de la tasa de desempleo entre 2010 y 2022.

In [104]:
df2 = pd.pivot_table(df, index = 'País', values = ['PIB per cápita (PPA, USD internacionales)',
                                                   'Tasa de desempleo (%)'],
                     aggfunc='mean').reset_index()
df2

        País  PIB per cápita (PPA, USD internacionales)  Tasa de desempleo (%)
0  Argentina                                  21,970.33                   8.26
1    Bolivia                                   9,230.50                   3.54
2     Brazil                                  15,821.96                  10.16
3      Chile                                  23,883.23                   7.76
4   Colombia                                  14,439.52                  10.44
5    Ecuador                                  11,586.61                   3.83
6   Paraguay                                  13,255.63                   5.63
7       Peru                                  12,397.29                   3.92
8    Uruguay                                  23,539.09                   7.76

A continuación se muestra, para cada país, el valor promedio y la desviación estándar del PIB per cápita PPA y el máximo y mínimo de la tasa de desempleo en el período 2010-2022.

In [105]:
df3 = pd.pivot_table(df, index = 'País', values = ['PIB per cápita (PPA, USD internacionales)',
                                                   'Tasa de desempleo (%)'],
                     aggfunc={'PIB per cápita (PPA, USD internacionales)':['mean','std'],
                              'Tasa de desempleo (%)':['min', 'max']}).reset_index()
df3

        País PIB per cápita (PPA, USD internacionales)           \
                                                  mean      std
0  Argentina                                 21,970.33 3,420.51
1    Bolivia                                  9,230.50 1,878.14
2     Brazil                                 15,821.96 1,562.51
3      Chile                                 23,883.23 3,502.45
4   Colombia                                 14,439.52 2,675.46
5    Ecuador                                 11,586.61 1,610.92
6   Paraguay                                 13,255.63 1,665.61
7       Peru                                 12,397.29 1,934.33
8    Uruguay                                 23,539.09 4,249.51

  Tasa de desempleo (%)
                    max  min
0                 11.46 6.80
1                  7.90 2.02
2                 13.70 6.75
3                 11.18 6.36
4                 15.57 8.57
5                  6.08 2.91
6                  7.55 4.08
7                  7.18 3.21
8                 10.41 6.31

## Transponer un dataframe

Dado que un dataframe es una matriz, lo podemos transponer.

In [106]:
# Dataframe inicial
df_desempleo

Año,País,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Argentina,7.71,7.18,7.22,7.10,7.27,NaN,NaN,8.35,9.22,9.84,11.46,8.74,6.80
1,Bolivia,NaN,2.25,2.07,2.44,2.02,3.11,3.50,3.65,3.52,3.68,7.90,4.94,3.45
2,Brazil,NaN,7.58,7.25,7.07,6.75,8.54,11.58,12.79,12.33,11.94,13.70,13.16,9.23
3,Chile,8.55,7.49,6.79,6.36,6.76,6.61,6.93,7.30,7.67,7.56,11.18,9.42,8.33
4,Colombia,11.15,10.29,9.96,9.25,8.80,8.57,8.92,9.09,9.36,10.28,15.57,13.90,10.54
5,Ecuador,4.09,3.46,3.23,2.91,3.28,3.42,4.39,3.71,3.40,3.70,6.08,4.43,3.67
6,Paraguay,4.57,4.67,4.08,4.38,5.03,4.56,5.25,6.14,6.22,6.59,7.55,7.33,6.76
7,Peru,3.60,3.48,3.24,3.58,3.21,3.27,3.74,3.69,3.49,3.38,7.18,5.10,4.00
8,Uruguay,7.16,6.31,6.45,6.44,6.55,7.49,7.84,7.89,8.34,8.84,10.41,9.33,7.88

In [107]:
df_desempleo_20 = df_desempleo.transpose()
df_desempleo_20

,0,1,2,3,4,5,6,7,8
Año,,,,,,,,,
País,Argentina,Bolivia,Brazil,Chile,Colombia,Ecuador,Paraguay,Peru,Uruguay
2010,7.71,NaN,NaN,8.55,11.15,4.09,4.57,3.60,7.16
2011,7.18,2.25,7.58,7.49,10.29,3.46,4.67,3.48,6.31
2012,7.22,2.07,7.25,6.79,9.96,3.23,4.08,3.24,6.45
2013,7.10,2.44,7.07,6.36,9.25,2.91,4.38,3.58,6.44
2014,7.27,2.02,6.75,6.76,8.80,3.28,5.03,3.21,6.55
2015,NaN,3.11,8.54,6.61,8.57,3.42,4.56,3.27,7.49
2016,NaN,3.50,11.58,6.93,8.92,4.39,5.25,3.74,7.84
2017,8.35,3.65,12.79,7.30,9.09,3.71,6.14,3.69,7.89
2018,9.22,3.52,12.33,7.67,9.36,3.40,6.22,3.49,8.34
2019,9.84,3.68,11.94,7.56,10.28,3.70,6.59,3.38,8.84
2020,11.46,7.90,13.70,11.18,15.57,6.08,7.55,7.18,10.41
2021,8.74,4.94,13.16,9.42,13.90,4.43,7.33,5.10,9.33
2022,6.80,3.45,9.23,8.33,10.54,3.67,6.76,4.00,7.88

In [110]:
# Dataframe transpuesto
df_desempleo_2 = df_desempleo.set_index('País').transpose().reset_index()
df_desempleo_2

País,Año,Argentina,Bolivia,Brazil,Chile,Colombia,Ecuador,Paraguay,Peru,Uruguay
0,2010,7.71,NaN,NaN,8.55,11.15,4.09,4.57,3.60,7.16
1,2011,7.18,2.25,7.58,7.49,10.29,3.46,4.67,3.48,6.31
2,2012,7.22,2.07,7.25,6.79,9.96,3.23,4.08,3.24,6.45
3,2013,7.10,2.44,7.07,6.36,9.25,2.91,4.38,3.58,6.44
4,2014,7.27,2.02,6.75,6.76,8.80,3.28,5.03,3.21,6.55
5,2015,NaN,3.11,8.54,6.61,8.57,3.42,4.56,3.27,7.49
6,2016,NaN,3.50,11.58,6.93,8.92,4.39,5.25,3.74,7.84
7,2017,8.35,3.65,12.79,7.30,9.09,3.71,6.14,3.69,7.89
8,2018,9.22,3.52,12.33,7.67,9.36,3.40,6.22,3.49,8.34
9,2019,9.84,3.68,11.94,7.56,10.28,3.70,6.59,3.38,8.84
10,2020,11.46,7.90,13.70,11.18,15.57,6.08,7.55,7.18,10.41
11,2021,8.74,4.94,13.16,9.42,13.90,4.43,7.33,5.10,9.33
12,2022,6.80,3.45,9.23,8.33,10.54,3.67,6.76,4.00,7.88

## Reshape del dataframe

Transformando Formatos: de long a wide y de wide a long.


**Formato Largo (Long):** Cada observación está en su propia fila. (Ej: Tenemos columnas de País, Año, Indicador, Valor, por lo que cada fila es una observación). Es el formato ideal para almacenar datos.

**Formato Ancho (Wide):** Cada fila representa una unidad de observación (como un país) y las variables se extienden a lo largo de las columnas (Ej: Country, GDP_2010, GDP_2011, GDP_2012). Es ideal para analizar los datos.

### Pasar de wide a long

In [111]:
# Dataframe original
df_desempleo

Año,País,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Argentina,7.71,7.18,7.22,7.10,7.27,NaN,NaN,8.35,9.22,9.84,11.46,8.74,6.80
1,Bolivia,NaN,2.25,2.07,2.44,2.02,3.11,3.50,3.65,3.52,3.68,7.90,4.94,3.45
2,Brazil,NaN,7.58,7.25,7.07,6.75,8.54,11.58,12.79,12.33,11.94,13.70,13.16,9.23
3,Chile,8.55,7.49,6.79,6.36,6.76,6.61,6.93,7.30,7.67,7.56,11.18,9.42,8.33
4,Colombia,11.15,10.29,9.96,9.25,8.80,8.57,8.92,9.09,9.36,10.28,15.57,13.90,10.54
5,Ecuador,4.09,3.46,3.23,2.91,3.28,3.42,4.39,3.71,3.40,3.70,6.08,4.43,3.67
6,Paraguay,4.57,4.67,4.08,4.38,5.03,4.56,5.25,6.14,6.22,6.59,7.55,7.33,6.76
7,Peru,3.60,3.48,3.24,3.58,3.21,3.27,3.74,3.69,3.49,3.38,7.18,5.10,4.00
8,Uruguay,7.16,6.31,6.45,6.44,6.55,7.49,7.84,7.89,8.34,8.84,10.41,9.33,7.88

In [112]:
# Convertir a formato long
df_largo_desempleo = pd.melt(
    df_desempleo,
    id_vars=['País'], # Columnas que se mantienen fijas
    var_name='Año', # Nombre de la nueva columna de variables
    value_name='Desempleo (%)' # Nombre de la nueva columna de valores
)
df_largo_desempleo

          País   Año  Desempleo (%)
0    Argentina  2010           7.71
1      Bolivia  2010            NaN
2       Brazil  2010            NaN
3        Chile  2010           8.55
4     Colombia  2010          11.15
..         ...   ...            ...
112   Colombia  2022          10.54
113    Ecuador  2022           3.67
114   Paraguay  2022           6.76
115       Peru  2022           4.00
116    Uruguay  2022           7.88

[117 rows x 3 columns]

El dataframe del Banco Mundial, que tiene forma de panel de datos y es wide, también lo podemos convertir a long.

In [113]:
df

,País,Año,"PIB per cápita (PPA, USD internacionales)","Gasto en salud per cápita (PPA, USD internacionales)",Esperanza de vida (años),Tasa de desempleo (%)
0,Argentina,2022,"29,804.08","3,006.98",75.81,6.80
1,Argentina,2021,"26,300.27","2,895.42",73.95,8.74
2,Argentina,2020,"22,393.35","2,389.92",75.88,11.46
3,Argentina,2019,"23,516.83","2,379.69",76.85,9.84
4,Argentina,2018,"24,410.39","2,483.24",76.77,9.22
...,...,...,...,...,...,...
112,Uruguay,2014,"21,867.81","1,785.00",77.19,6.55
113,Uruguay,2013,"20,661.38","1,709.24",76.95,6.44
114,Uruguay,2012,"19,495.42","1,615.10",76.69,6.45
115,Uruguay,2011,"19,135.36","1,574.28",76.61,6.31
116,Uruguay,2010,"17,872.54","1,475.01",76.69,7.16

In [114]:
df_largo = pd.melt(
    df,
    id_vars=['País', 'Año'], # Columnas que se mantienen fijas
    var_name='Indicador', # Nombre de la nueva columna de variables
    value_name='Valor' # Nombre de la nueva columna de valores
)
df_largo

          País   Año                                  Indicador     Valor
0    Argentina  2022  PIB per cápita (PPA, USD internacionales) 29,804.08
1    Argentina  2021  PIB per cápita (PPA, USD internacionales) 26,300.27
2    Argentina  2020  PIB per cápita (PPA, USD internacionales) 22,393.35
3    Argentina  2019  PIB per cápita (PPA, USD internacionales) 23,516.83
4    Argentina  2018  PIB per cápita (PPA, USD internacionales) 24,410.39
..         ...   ...                                        ...       ...
463    Uruguay  2014                      Tasa de desempleo (%)      6.55
464    Uruguay  2013                      Tasa de desempleo (%)      6.44
465    Uruguay  2012                      Tasa de desempleo (%)      6.45
466    Uruguay  2011                      Tasa de desempleo (%)      6.31
467    Uruguay  2010                      Tasa de desempleo (%)      7.16

[468 rows x 4 columns]

### Pasar de long a wide

Para pasar de formato long a wide se utilizan las tablas pivote que vimos previamente.